### ISSUE TITLE
Scheduling property is ignored

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/qps-pipeline#10]
Details:
1) within thw suite I want to run following parameter is set:
<parameter name="jenkinsRegressionPipeline"
		value="MMF-Andoid-Minimal-Acceptance-Regression-Pipeline" />

2) following pipeline job is created on Jenkins:
https://ua.qaprosoft.com/jenkins/job/Pipeline/job/MMF-Andoid-Minimal-Acceptance-Regression-Pipeline/

in wich following checkbox is checked: Build periodically
and the schedule is set according to the same parameter from within suite:
<parameter name="jenkinsPipelineScheduling" value="H 1 * * 1-5" />

3) there're no any errors in pipeline job or PipelineDSL job
https://ua.qaprosoft.com/jenkins/job/Pipeline/job/MMF-Andoid-Minimal-Acceptance-Regression-Pipeline/65/console

https://ua.qaprosoft.com/jenkins/job/Management_Jobs/job/PipelineDSL/39/consoleFull

**Comment by vdelendik** [comment]
not a bug. as I see job is scheduled and started by timer:
https://ua.qaprosoft.com/jenkins/job/Pipeline/job/MMF-Andoid-Minimal-Acceptance-Regression-Pipeline/66/console
pay attention that GMT time is used for now because no one requested any updates with this
