### ISSUE TITLE
Automation jobs started on multiple environments after triggering Pipeline job

### ISSUE THREAD

**Issue by rzubkouski** [qaprosoft/qps-pipeline#119]
Summary: 
After setting of android pipeline job on specific environment (e.g. MASTER_BETA, QA_REMOTE_PROD) all specific jobs (e.g. SANITY, SMOKE etc.) are triggered on 2 envs: 1) which was determined in pipeline job 2) general env (INT | BETA | PROD)

**Comment by vdelendik** [comment]
fix delivered in 2.8 pipeline
