### ISSUE TITLE
Remove hardcoded url from the scripts

### ISSUE THREAD

**Issue by kolyakrasnik** [qaprosoft/qps-pipeline#12]
We use hardcoded URL in the scripts which cause automation fails. File for the reference : https://github.com/qaprosoft/qps-pipeline/blob/master/src/com/qaprosoft/jenkins/repository/jobdsl/Job.groovy
**line 281**

Some workaround https://github.com/qaprosoft/qps-pipeline/commit/9dacd546fa6e3c32726a9c31b60aff6e3b2e654f

**Comment by vdelendik** [comment]
resolved in 2.2+
