### ISSUE TITLE
Adjust thread number counting to do it automatically during test run

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/qps-pipeline#120]
...to avoid following errors:

org.openqa.selenium.WebDriverException: cannot create session QPS-HUB-* on any hosts after 1 attempt(s) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 300.00 seconds
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: '00953bdc2828', ip: '172.18.0.28', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-24-generic', java.version: '1.8.0_151'
Driver info: driver.version: AndroidDriver

com.qaprosoft.carina.core.foundation.webdriver.DriverPool.createDriver(DriverPool.java:370)
com.qaprosoft.carina.core.foundation.webdriver.DriverPool.getDriver(DriverPool.java:146)
com.qaprosoft.carina.core.foundation.webdriver.DriverPool.getDriver(DriverPool.java:98)
com.qaprosoft.carina.core.foundation.webdriver.DriverPool.getDriver(DriverPool.java:67)
com.qaprosoft.carina.core.foundation.utils.factory.CustomTypePageFactory.initPage(CustomTypePageFactory.java:59)

**Comment by vdelendik** [comment]
won't fix. engineers should adjust it on their own as we can't predict so far about upcoming runs
