### ISSUE TITLE
investigate possibility to get more details about failures

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#169]
we took only failure reason like this one:
https://github.com/qaprosoft/qps-pipeline/blob/a204842249851ba17e93c6357075a0edcd68c84b/src/com/qaprosoft/jenkins/pipeline/impl/QARunner.groovy#L726

please investigate if it is possible to get more details as text. in case of compilation I'd like to have list of uncompiled classes with logs etc

**Comment by tsvrko** [comment]
done #171
