### ISSUE TITLE
get list of grid Devices using deviceName property

### ISSUE THREAD

**Issue by tsvrko** [qaprosoft/qps-pipeline#175]
Since values deviceName and browserName differ for now, list of devices based on browserName is not applicable anymore. We need direct way to get correct (not containing browser names) list of devices for use as default pool.

**Comment by vdelendik** [comment]
idea to exclude unavailable devices from DevicePool

**Comment by vdelendik** [comment]
out-of-dated as capabilities is general filed as of now and only Zafira will have valid devices tree
