### ISSUE TITLE
add suite owner as default recipient for build failure email

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#184]
earlier we added full email_list as recepients for build failure but it was removed due to the complains about a lot of false alarm during infrastructure issues with cloud etc.
So we keep only sending to ADMIN_EMAILS.
Let's try to add into this list suite owner as well so he can react faster to the issue

**Comment by tsvrko** [comment]
done https://github.com/qaprosoft/qps-pipeline/pull/196
