### ISSUE TITLE
investigate how double onPullrequest and onPush actions work

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#185]
from time to time we discover issues with onPush and onPullrequests jobs which are started in parallel.
using this ticket let's investigate deeper how it works and after confirmation the issues we should prohibit parallel execution.

For onPush it was discovered that local "clean install" corrupt maven-metadata-local.xml for the project and noone could deploy changes later until we fix xml tags manually.

**Comment by tsvrko** [comment]
not reproduced
