### ISSUE TITLE
terminated by timeout test is marked as "BUILD FAILURE"

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#189]
Find a way to determine below use-case as aborted by timeout. No extra details should be added into the test-run comment in this case.

Below is the stracktrace of the failure:

15:39:00 Sending interrupt signal to process
15:39:00 Cancelling nested steps due to timeout
....
15:39:01 [INFO] BUILD FAILURE
15:39:01 [INFO] ------------------------------------------------------------------------
15:39:01 [INFO] Total time: 02:59 h
15:39:01 [INFO] Finished at: 2018-10-15T22:39:00+00:00
15:39:01 [INFO] Final Memory: 194M/530M
15:39:01 [INFO] ------------------------------------------------------------------------
15:39:01 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18:test (default-test) on project tests: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
15:39:01 [ERROR] Command was /bin/sh -c cd /tmp/jenkins/.../target/surefire/surefire_05489048675361334917tmp
...
exception: script returned exit code 143
[Pipeline] echo
exception class: hudson.AbortException

**Comment by tsvrko** [comment]
done https://github.com/qaprosoft/qps-pipeline/pull/190
