### ISSUE TITLE
3.3: emailExt notification has invalid link to ZafiraPeport

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#199]
ZafiraReport: https://<host>/jenkins/job/<job>/49/"ZafiraReport"
pay attention to the quotes around "ZafiraReport" inside the url.

please fix as a hotfix inside 3.3 release and merge to master

**Comment by tsvrko** [comment]
done https://github.com/qaprosoft/qps-pipeline/commit/3f75a620749b5907c20d9dd84ef906060d5eecf2
