### ISSUE TITLE
Possibility to add ExtensibleChoise parameter from suite for job generating is required

### ISSUE THREAD

**Issue by maksimsarychau** [qaprosoft/qps-pipeline#273]
Something like <parameter name="extensibleChoice::extensible_editable_choice::Select description" value="" />

And have in Jenkins following: 
![image](https://user-images.githubusercontent.com/4455896/50935064-089bdf80-146b-11e9-9d23-eb27acc3b58f.png)

**Comment by tsvrko** [comment]
it is recommended to use stringParam instead
