### ISSUE TITLE
Test run report emails are not sent when there is any failure in test results

### ISSUE THREAD

**Issue by deNatallia** [qaprosoft/qps-pipeline#289]
[Pipeline] httpRequest
HttpMethod: POST
URL: https://***.qaprosoft.cloud/zafira-ws/api/tests/runs/a16d9bb9-80e6-48cb-8aba-0c4fc509fe04/emailFailure?suiteOwner=true&suiteRunner=false
Content-type: application/json
Authorization: *****
Sending request to url: https://***.qaprosoft.cloud/zafira-ws/api/tests/runs/a16d9bb9-80e6-48cb-8aba-0c4fc509fe04/emailFailure?suiteOwner=true&suiteRunner=false
Response Code: HTTP/1.1 200 OK
Success code from [200‥401]

**Comment by tsvrko** [comment]
Detalization: email is sent to admins, necessary to enable sending for user if test has finished successfully (Ex. PASSED/FAILED), and to admins if it is ABORTED
