### ISSUE TITLE
Passed tests can displayed as skipped

### ISSUE THREAD

**Issue by deNatallia** [qaprosoft/qps-pipeline#305]
Test is PASSED in zafira logs, but its status is SKIPED

**Comment by deNatallia** [comment]
![screen shot 2019-02-06 at 2 16 36 pm](https://user-images.githubusercontent.com/24562001/52338154-a529b100-2a1a-11e9-88e6-c5bee31a261e.png)

**Comment by tsvrko** [comment]
can not reproduce
