### ISSUE TITLE
Some of finished tests are shown as Queued

### ISSUE THREAD

**Issue by deNatallia** [qaprosoft/qps-pipeline#306]
> 10:58:29 [INFO] Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 917.014 s - in TestSuite
> 10:58:30 [INFO] 
> 10:58:30 [INFO] Results:
> 10:58:30 [INFO] 
> 10:58:30 [INFO] Tests run: 24, Failures: 0, Errors: 0, Skipped: 0

but in Zafira 

![screen shot 2019-02-06 at 2 33 31 pm](https://user-images.githubusercontent.com/24562001/52338715-39e0de80-2a1c-11e9-9173-6129f1bd72f5.png)

**Comment by tsvrko** [comment]
can not reproduce
