### ISSUE TITLE
Testrail integraition. Testrun name isn't updated after aborting jenkins job

### ISSUE THREAD

**Issue by KirillBugrim** [qaprosoft/qps-pipeline#312]
I update app_version property in my code. But if I abort the jenkins job, the new value  of app_version is not pulled up, and the value of the test run name is created by default

**Comment by tsvrko** [comment]
Presence of app_version in TestRail run name is impossible because of system architecture specifics. 
**app_version** is known only on test finish when TestRun is initialized with new config.xml populated with run data.
On *abort* java process is killed and data is lost.
