### ISSUE TITLE
Tests execution is getting skipped in Jenkins for newly added or renamed test methods

### ISSUE THREAD

**Issue by SergeiZagriychuk** [qaprosoft/qps-pipeline#342]
Steps to reproduce:
1) Run some test suite and check that all tests were executed properly.
2) Rename some of test methods related to the suite
3) Rerun tests once again (start new run, rerun_failures=false)
4) Observe execution logs
Actual result: renamed tests weren't executed. In logs it's said that test was started and then immediately passed. at the same time they're registered in zafira as passed tests

Link to zafira run:
https://ua.qaprosoft.cloud/zafira/#!/tests/runs/20431

Piece of executions logs from jenkins (in DEBUG mode):
13:39:36  2019-03-25 13:39:36 Messager [TestNG-tests-1-32] [INFO] INFO:  TEST [Product Test - testCartItemContentOnCheckOutPage1] STARTED at [13:39:36 2019-03-25]
13:39:36  2019-03-25 13:39:36 ZafiraConfigurator [TestNG-tests-1-32] [DEBUG] testName: Product Test - testCartItemContentOnCheckOutPage1
13:39:36  2019-03-25 13:39:36 Ownership [TestNG-tests-1-32] [DEBUG] Method 'public void com.underarmour.mmt.qa.product.ProductTest.testCartItemContentOnCheckOutPage1()' primary owner is: atataranovich
13:39:36  2019-03-25 13:39:36 ZafiraConfigurator [TestNG-tests-1-32] [DEBUG] primaryOwner: atataranovich
13:39:36  2019-03-25 13:39:36 Ownership [TestNG-tests-1-32] [DEBUG] Method 'public void com.underarmour.mmt.qa.product.ProductTest.testCartItemContentOnCheckOutPage1()' primary owner is: atataranovich
13:39:36  2019-03-25 13:39:36 ZafiraConfigurator [TestNG-tests-1-32] [DEBUG] primaryOwner: atataranovich
13:39:36  2019-03-25 13:39:36 Ownership [TestNG-tests-1-32] [DEBUG] Method 'public void com.underarmour.mmt.qa.product.ProductTest.testCartItemContentOnCheckOutPage1()' secondary owner is: 
13:39:36  2019-03-25 13:39:36 ZafiraConfigurator [TestNG-tests-1-32] [DEBUG] secondaryOwner: 
13:39:36  2019-03-25 13:39:36 ZafiraConfigurator [TestNG-tests-1-32] [DEBUG] testMethodName: testCartItemContentOnCheckOutPage1
13:39:36  2019-03-25 13:39:36 ZafiraConfigurator [TestNG-tests-1-32] [DEBUG] runCount: 0
13:39:36  2019-03-25 13:39:36 IDriverPool [TestNG-tests-1-32] [DEBUG] Current device is null for thread: 32
13:39:36  2019-03-25 13:39:36 ZafiraConfigurator [TestNG-tests-1-32] [DEBUG] Unable to detect current device for threadId: 32
13:39:36  2019-03-25 13:39:36 ZafiraConfigurator [TestNG-tests-1-32] [DEBUG] Collecting TestTags...
13:39:36  2019-03-25 13:39:36 PriorityManager [TestNG-tests-1-32] [DEBUG] suitePriority is: null
13:39:36  2019-03-25 13:39:36 ZafiraConfigurator [TestNG-tests-1-32] [DEBUG] Collecting TestRail Tags...
13:39:36  2019-03-25 13:39:36 ITestRailManager [TestNG-tests-1-32] [DEBUG] TestRail test case uuid '2298804' is registered.
13:39:36  2019-03-25 13:39:36 ZafiraConfigurator [TestNG-tests-1-32] [DEBUG] Found 0 new TestRail tags
13:39:36  2019-03-25 13:39:36 ZafiraConfigurator [TestNG-tests-1-32] [DEBUG] Collecting qTest Tags...
13:39:36  2019-03-25 13:39:36 ZafiraConfigurator [TestNG-tests-1-32] [DEBUG] Found 0 new qTest tags
13:39:36  2019-03-25 13:39:36 ZafiraConfigurator [TestNG-tests-1-32] [DEBUG] Found 0 new TestTags
13:39:36  2019-03-25 13:39:36 ZafiraConfigurator [TestNG-tests-1-32] [DEBUG] testName: Product Test - testCartItemContentOnCheckOutPage1
13:39:36  2019-03-25 13:39:36 CarinaListener [TestNG-tests-1-32] [DEBUG] current method: com.underarmour.mmt.qa.product.ProductTest.testCartItemContentOnCheckOutPage1
13:39:36  2019-03-25 13:39:36 CarinaListener [TestNG-tests-1-32] [DEBUG] analyze method for dependency: testCartItemContentOnBagPage1
13:39:36  2019-03-25 13:39:36 CarinaListener [TestNG-tests-1-32] [DEBUG] analyze method for dependency: testCartItemContentOnCheckOutPage1
13:39:36  2019-03-25 13:39:36 CarinaListener [TestNG-tests-1-32] [DEBUG] analyze method for dependency: testClickingUAProductNameOrImageOnBagPageRedirectsToPDP1
13:39:36  2019-03-25 13:39:36 CarinaListener [TestNG-tests-1-32] [DEBUG] analyze method for dependency: testClickingUAProductNameOrImageOnCheckoutPageRedirectsToPDP1
13:39:36  2019-03-25 13:39:36 IDriverPool [TestNG-tests-1-32] [DEBUG] Current device is null for thread: 32
13:39:36  2019-03-25 13:39:36 IDriverPool [TestNG-tests-1-32] [DEBUG] Current device is null for thread: 32
13:39:36  2019-03-25 13:39:36 Messager [TestNG-tests-1-32] [INFO] INFO:  TEST [Product Test - testCartItemContentOnCheckOutPage1] PASSED at [13:39:36 2019-03-25]
13:39:36  2019-03-25 13:39:36 IDriverPool [TestNG-tests-1-32] [DEBUG] Current device is null for thread: 32
13:39:36  2019-03-25 13:39:36 TestNamingUtil [TestNG-tests-1-32] [DEBUG] Releasing information about test: Product Test - testCartItemContentOnCheckOutPage1
13:39:36  2019-03-25 13:39:36 ZafiraConfigurator [TestNG-tests-1-32] [DEBUG] testName: Product Test - testCartItemContentOnCheckOutPage1

**Comment by SergeiZagriychuk** [comment]
Fixed by @tsvrko in https://github.com/qaprosoft/qps-pipeline/commit/68bfe870529606b1f893e8c690aa3c342037623d

**Comment by SergeiZagriychuk** [comment]
additional update needed @tsvrko

**Comment by tsvrko** [comment]
updated in 4.0.1
