### ISSUE TITLE
Scan repository does not work

### ISSUE THREAD

**Issue by mparkhomenko** [qaprosoft/qps-pipeline#411]
**Environment:** 
	**Chrome** 75.0.3770.80
	**MacOS** Mojave 10.14.5
	**Repository** https://github.com/mrMakkey/carina-pizza

**How to test:** 
1. Login
2. Open https://stage.qaprosoft.farm/app/tests/runs
3. Click [Test launcher]
4. Click [ADD REPO]
5. Choose organization and repo
6. Click [SCAN]

**Description:**
	Inside the repository is Carina Framework with web tests created on it that have @Test annotations.
	No errors were noticed in the browser console.

**Actual Result:**
	After pressing the [SCAN] button, an infinite scan of the repository begins.

<img width="939" alt="Снимок экрана 2019-06-11 в 16 40 29" src="https://user-images.githubusercontent.com/47244665/59280814-dc30fd00-8c6e-11e9-8f28-ff55b1e02205.png">

<img width="745" alt="Снимок экрана 2019-06-11 в 16 59 14" src="https://user-images.githubusercontent.com/47244665/59280825-e18e4780-8c6e-11e9-8d04-b5073fdefb02.png">

**Comment by tsvrko** [comment]
fixed in 4.2.2
