### ISSUE TITLE
Re-scan repository does not work

### ISSUE THREAD

**Issue by mparkhomenko** [qaprosoft/qps-pipeline#412]
Environment:
Chrome 75.0.3770.80
MacOS Mojave 10.14.5
Repository https://github.com/mrMakkey/carina-pizza

How to test:
1. Login
2. Open https://stage.qaprosoft.farm/app/tests/runs
3. Click [Test launcher]
4. Hover over the desired repository in the right panel
5. Click on the settings icon
6. Click [RE-SCAN]

Description:
Inside the repository is Carina Framework with web tests created on it that have @test annotations.
To test rescan, I added a new test to the repository ([NewSampleTest.java](https://github.com/mparkhomenko/carina-pizza/tree/master/src/test/java/com/qaprosoft/carina/demo)).
No errors were noticed in the browser console.

Actual Result:
After pressing the [RE-SCAN] button, a new test (template) was not created in the left panel.

**Comment by vdelendik** [comment]
fixed in 4.6+
