### ISSUE TITLE
reuse Jenkinsfile pipeline script from repo for "build" job

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#470]
onPush-repo job has some default qps actions developed. At the same time we should provide possibility to generate customer specific build jobs using Jenkinsfile in their repositories

**Comment by vdelendik** [comment]
Repository->generateCiItems shouold be updated

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/555

**Comment by okamara** [comment]
Tested.Fixed.
