### ISSUE TITLE
Delete hardcoded -Dinit_retry_count=0

### ISSUE THREAD

**Issue by kolyakrasnik** [qaprosoft/qps-pipeline#483]
We have hardcoded parameter in QARunner -> getMavenGoals() method. Please, remove it. https://github.com/qaprosoft/qps-pipeline/blob/4dab4d84b4559fb46fbffb8864c800bd46200600/src/com/qaprosoft/jenkins/pipeline/runner/maven/QARunner.groovy#L783

**Comment by vdelendik** [comment]
4.8-beta1+
