### ISSUE TITLE
register repository shouldn't use global GITHUB_ORGANIZATION

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#486]
investigate possibility to avoid GITHUB_HOST and GITHUB_ORGANIZATION usage from global variables.

Repository.groovy:
    private void prepare() {
        scmClient.clone(true) //do shallow clone during repo registration to verify if Jenkinsfile exists inside

and clone method generate url based on global vars

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/488

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/501
