### ISSUE TITLE
onPush: do not make a call to null/grid/admin/ProxyInfo

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#492]
16:53:52  java.net.MalformedURLException: no protocol: null/grid/admin/ProxyInfo
16:53:52  	at java.net.URL.<init>(URL.java:593)
16:53:52  	at java.net.URL.<init>(URL.java:490)
16:53:52  	at java.net.URL.<init>(URL.java:439)
16:53:52  	at org.codehaus.groovy.runtime.ResourceGroovyMethods.toURL(ResourceGroovyMethods.java:2399)
16:53:52  	at org.codehaus.groovy.runtime.dgm$1014.invoke(Unknown Source)
16:53:52  	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
16:53:52  	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
16:53:52  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
16:53:52  	at com.qaprosoft.jenkins.jobdsl.selenium.grid.ProxyInfo.getDevicesList(ProxyInfo.groovy:26)
16:53:52  	at com.qaprosoft.jenkins.jobdsl.selenium.grid.ProxyInfo$getDevicesList.call(Unknown Source)
16:53:52  	at com.qaprosoft.jenkins.jobdsl.factory.pipeline.TestJobFactory.getDevices(TestJobFactory.groovy:218)
16:53:52  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:53:52  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:53:52  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:53:52  	at java.lang.reflect.Method.invoke(Method.java:498)
16:53:52  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
16:53:52  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
16:53:52  	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
16:53:52  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
16:53:52  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)
16:53:52  	at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
16:53:52  	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:446)
16:53:52  	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:371)
16:53:52  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
16:53:52  	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
16:53:52  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
16:53:52  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
16:53:52  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
16:53:52  	at com.qaprosoft.jenkins.jobdsl.factory.pipeline.TestJobFactory$_create_closure1$_closure4.doCall(TestJobFactory.groovy:115)
16:53:52  	at com.qaprosoft.jenkins.jobdsl.factory.pipeline.TestJobFactory$_create_closure1$_closure4.doCall(TestJobFactory.groovy)
16:53:52  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:53:52  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:53:52  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:53:52  	at java.lang.reflect.Method.invoke(Method.java:498)
16:53:52  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
16:53:52  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
16:53:52  	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
16:53:52  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
16:53:52  	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
16:53:52  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
16:53:52  	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:57)
16:53:52  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
16:53:52  	at javaposse.jobdsl.dsl.ContextHelper.executeInContext(ContextHelper.groovy:16)
16:53:52  	at javaposse.jobdsl.dsl.ContextHelper$executeInContext.call(Unknown Source)
16:53:52  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
16:53:52  	at javaposse.jobdsl.dsl.ContextHelper$executeInContext.call(Unknown Source)
16:53:52  	at javaposse.jobdsl.dsl.Job.parameters(Job.groovy:330)
16:53:52  	at sun.reflect.GeneratedMethodAccessor1889.invoke(Unknown Source)
16:53:52  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:53:52  	at java.lang.reflect.Method.invoke(Method.java:498)
16:53:52  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
16:53:52  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
16:53:52  	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
16:53:52  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
16:53:52  	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
16:53:52  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
16:53:52  	at com.qaprosoft.jenkins.jobdsl.factory.pipeline.TestJobFactory$_create_closure1.doCall(TestJobFactory.groovy:54)
16:53:52  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:53:52  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:53:52  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:53:52  	at java.lang.reflect.Method.invoke(Method.java:498)
16:53:52  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
16:53:52  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
16:53:52  	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
16:53:52  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
16:53:52  	at groovy.lang.Closure.call(Closure.java:414)
16:53:52  	at groovy.lang.Closure.call(Closure.java:430)
16:53:52  	at org.codehaus.groovy.runtime.DefaultGroovyMethods.with(DefaultGroovyMethods.java:242)
16:53:52  	at org.codehaus.groovy.runtime.dgm$758.invoke(Unknown Source)
16:53:52  	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:251)
16:53:52  	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
16:53:52  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
16:53:52  	at com.qaprosoft.jenkins.jobdsl.factory.pipeline.TestJobFactory.create(TestJobFactory.groovy:43)
16:53:52  	at com.qaprosoft.jenkins.jobdsl.factory.pipeline.TestJobFactory$create.call(Unknown Source)
16:53:52  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
16:53:52  	at com.qaprosoft.jenkins.jobdsl.factory.view.ListViewFactory$create.call(Unknown Source)
16:53:52  	at com.qaprosoft.jenkins.Factory$_run_closure1.doCall(Factory.groovy:24)
16:53:52  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:53:52  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:53:52  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:53:52  	at java.lang.reflect.Method.invoke(Method.java:498)
16:53:52  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
16:53:52  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
16:53:52  	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
16:53:52  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
16:53:52  	at groovy.lang.Closure.call(Closure.java:414)
16:53:52  	at groovy.lang.Closure.call(Closure.java:430)
16:53:52  	at org.codehaus.groovy.runtime.DefaultGroovyMethods.callClosureForMapEntry(DefaultGroovyMethods.java:5278)
16:53:52  	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2117)
16:53:52  	at org.codehaus.groovy.runtime.dgm$164.invoke(Unknown Source)
16:53:52  	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
16:53:52  	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
16:53:52  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
16:53:52  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
16:53:52  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
16:53:52  	at com.qaprosoft.jenkins.Factory.run(Factory.groovy:18)
16:53:52  	at com.qaprosoft.jenkins.Factory$run.call(Unknown Source)
16:53:52  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
16:53:52  	at com.qaprosoft.jenkins.Factory$run.call(Unknown Source)
16:53:52  	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScript(AbstractDslScriptLoader.groovy:132)
16:53:52  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:53:52  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:53:52  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:53:52  	at java.lang.reflect.Method.invoke(Method.java:498)
16:53:52  	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
16:53:52  	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
16:53:52  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
16:53:52  	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:64)
16:53:52  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
16:53:52  	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScriptEngine(AbstractDslScriptLoader.groovy:106)
16:53:52  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:53:52  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:53:52  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:53:52  	at java.lang.reflect.Method.invoke(Method.java:498)
16:53:52  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
16:53:52  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
16:53:52  	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
16:53:52  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
16:53:52  	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
16:53:52  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
16:53:52  	at javaposse.jobdsl.dsl.AbstractDslScriptLoader$_runScripts_closure1.doCall(AbstractDslScriptLoader.groovy:59)
16:53:52  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:53:52  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:53:52  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:53:52  	at java.lang.reflect.Method.invoke(Method.java:498)
16:53:52  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
16:53:52  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
16:53:52  	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
16:53:52  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
16:53:52  	at groovy.lang.Closure.call(Closure.java:414)
16:53:52  	at groovy.lang.Closure.call(Closure.java:430)
16:53:52  	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2040)
16:53:52  	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2025)
16:53:52  	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2078)
16:53:52  	at org.codehaus.groovy.runtime.dgm$165.invoke(Unknown Source)
16:53:52  	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
16:53:52  	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
16:53:52  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
16:53:52  	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScripts(AbstractDslScriptLoader.groovy:46)
16:53:52  	at javaposse.jobdsl.plugin.ExecuteDslScripts.perform(ExecuteDslScripts.java:341)
16:53:52  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
16:53:52  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
16:53:52  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
16:53:52  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
16:53:52  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
16:53:52  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16:53:52  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16:53:52  	at java.lang.Thread.run(Thread.java:748)

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/499

**Comment by vdelendik** [comment]
looks like obsolete code now
