### ISSUE TITLE
RegisterRepository factory: add default github_host parameter

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#495]
1) add default parametr for registerRepository job factory
github_host="github.com"
2) override GITHUB_HOST for Repository.register as we did for organization

**Comment by vdelendik** [comment]
related ticket: https://github.com/qaprosoft/zafira/issues/1681

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/498/

**Comment by vdelendik** [comment]
verified on my own
