### ISSUE TITLE
mark onPush job as fail in case of any problem with scm cloning

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#506]
real example when scan failed but job in SUCCEED:

23:52:01   > git fetch --no-tags --force --progress https://github.com/org/repo +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=15
23:52:01  ERROR: Error cloning remote repo 'origin'
23:52:01  hudson.plugins.git.GitException: Command "git fetch --no-tags --force --progress https://github.com/org/repo +refs/heads/*:refs/remotes/origin/* --depth=1" returned status code 128:
23:52:01  stdout: 
23:52:01  stderr: fatal: unable to access 'https://github.com/org/repo/': The requested URL returned error: 400
23:52:01  
23:52:01  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2042)
23:52:01  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1761)
23:52:01  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$400(CliGitAPIImpl.java:72)
23:52:01  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:442)
23:52:01  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:655)
23:52:01  	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1152)
23:52:01  	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1192)
23:52:01  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
23:52:01  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
23:52:01  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
23:52:01  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
23:52:01  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
23:52:01  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
23:52:01  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
23:52:01  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
23:52:01  	at java.lang.Thread.run(Thread.java:748)
[Pipeline] }
[Pipeline] // stage
[Pipeline] echo
23:52:01  Scan failed.
23:52:01  Error cloning remote repo 'origin'
....
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/519

**Comment by okamara** [comment]
Reverified by QA
