### ISSUE TITLE
Adjust "capabilities" field registration for launchers

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#510]
That's field is needed only for CI. On Zafira layer there is a good UI feature to handle it so field shouldn't be registered

**Comment by vdelendik** [comment]
this field will have comma separated list of capabilities. Using this list we can later detect provider, browser or device from the list and pick it automatically.

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/522/files

**Comment by okamara** [comment]
Reverified and created a separate bug https://github.com/qaprosoft/zafira/issues/1935
