### ISSUE TITLE
remove any reference onto the gc_BROWSER from pipeline code and docs

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#512]
in 4.8+ pipeline we redesigned capabilities detection. There is no need to have hardcoded global choice list of supported browsers anymore

**Comment by ilya-varchenya** [comment]
For that moment there is one mention in jenkins-master https://github.com/qaprosoft/jenkins-master/blob/e31a22bc122e300fec2934f9b4e1064c89e5da86/resources/configs/jp.ikedam.jenkins.plugins.extensible_choice_parameter.GlobalTextareaChoiceListProvider.xml#L12

**Comment by vdelendik** [comment]
@ilya-varchenya, please remove it completely on jenkins-master. it is recommended to submit new ticket in above project and assign it to 4.9 to track manual migration steps

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/113

**Comment by vdelendik** [comment]
@okamara to test this ticket please verify that we don't have any "browser" dropdown in the web test jobs.
Also after removing gc_BROWSER from "manage jenkins -> configure system" everything should work: registration, scanning, jobs execution.
Pay attention to the web tests (jobs) only

**Comment by okamara** [comment]
Web tests jobs not working for me.

**Comment by okamara** [comment]
Reverified and separate bug is created for private and public ports in set up ssh
