### ISSUE TITLE
jenkinsDefaultBrowser should be registered as part of the new capabilities field on jenkins

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#513]
we can think about global approach to define default capabilities from suite xml into the job.
parameter name="capabilities" value="browserName=chrome, browserVersion=77"
That's guarantee unified approach to deliver default capabilities from suite to CI and zafira

above value should be registered as capabilities field value on CI job

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/qps-pipeline/commit/dea906ec046c0ec30b2a7f3ec8aff3ceb4c62929

**Comment by okamara** [comment]
Reverified for 4.8. browserVersion is not visible after re-scan.

**Comment by okamara** [comment]
Reverified for 4.8. browserVersion is not visible after re-scan.

**Comment by vdelendik** [comment]
reviewed code and tested using custom branch: https://github.com/qaprosoft/carina-demo/blob/0374cd5730fd9d8e7dd38840d0e76e0389bc0fcd/src/test/resources/testng_suites/web.xml#L14

after rescan job has valid and fully customized caps:
http://demo.qaprosoft.com/jenkins/job/qaprosoft/job/carina-demo/job/Web-Demo-Test

![image](https://user-images.githubusercontent.com/4551455/70578480-ec467c80-1bbe-11ea-8428-66ae8eb6e9a7.png)

@okamara, please retest, maybe you provided your parameter with mistake or used invalid branch for rescan

**Comment by okamara** [comment]
Reverified: It doesn't work if I declare param like in top description ->
 <parameter name="capabilities" value="browserName=chrome, browserVersion=77" />

It works in this case -> <parameter name="capabilities" value="browserName=chrome; browserVersion=77"/>
@vdelendik what declaration should work both or only one with ":" ?

**Comment by okamara** [comment]
Reverified. Fixed.
