### ISSUE TITLE
remove any reference to DefaultPool from pipeline code and docs

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#514]
there is no need anymore in custom DefaultPool capability

**Comment by vdelendik** [comment]
done in 4.8

**Comment by okamara** [comment]
@vdelendik could you please add details how I can re-verify this issue?

**Comment by vdelendik** [comment]
@okamara, it was a feature for iOS and Android jobs only.
1) there is not anymore dedicated "devicePool" parameter for mobile jobs:
![image](https://user-images.githubusercontent.com/4551455/70670251-98549a00-1c89-11ea-81a7-493b85224c4b.png)
2) Default settings for capabilities filed should be:
Android job: "platformName=ANDOID;deviceName=ANY"
iOS job: "platformName=iOS;deviceName=ANY"
3) update temporary any mobile suite declaring exta parameter like:
	parameter name="jenkinsMobileDefaultPool" value="device1, device2, device3"
4) re-scan repo on updated branch
-> verify that capabilities field value is updated a little bit:
Android job: "platformName=ANDOID;deviceName=device1, device2, device3"
