### ISSUE TITLE
incorporate platform value as part of the new capabilities field

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#515]
1) remove all hidden parameters from jenkins jobs like:
configure addHiddenParameter('platform', '', 'iOS')
2) add those information as part of the capabilities filed:
capabilities.platform=iOS
or
capabilities.platformName=iOS

**Comment by vdelendik** [comment]
it has sense to adjust JobDSL and put default capabilities like platform and browserName based on job type.
For example web should have:
capabilities.browserName=chrome
api:
capabilities.platform=API

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/551/files

**Comment by vdelendik** [comment]
done
