### ISSUE TITLE
onPullRequest verification should do compilation if sonar is not configured

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#518]
For now we skipped all kind of actions if no sonarqube integrated.
It would be nice to keep compilation for all high level maven projects (pom.xml) in this case.
Also let's keep warning in log that we recommend to setup pr checker with sonar as well

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/qps-pipeline/commit/7daa60eeea71b64c0ea20bb7e312144dfd3e26d9

**Comment by okamara** [comment]
@vdelendik could you please add details how I can re-verify this issue?

**Comment by vdelendik** [comment]
@okamara, 
Prerequisites: 
1) GitHub pull request checker is configured globally in "manage jenkins->configure system"
2) repository is registered using valid github token
3) in github repository settings there is webhook added for your CI

Test scenario:
1) Send pull request to your repository with some changes
2) take a look into the onPullRequest-<repo> job console log
-> it should contain maven compilation steps and logs. Job is green/blue if no compilation failures detected in PR
3) update PR putting some syntax mistake in java code
-> onPullRequest job should be started and it's status should be red.
-> Appropriate failure should be marked on Github for PR link

**Comment by okamara** [comment]
Verified
