### ISSUE TITLE
adjust default value of new capabilities field based on the job type

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#523]
api job:
capabilities: '' //i.e. empty
web:
capabilities: browserName=chrome
android, ios:
capabilities: deviceName=ANY
web ios:
capabilities: browserName=safari, deviceName=ANY
web android:
capabilities: browserName=chrome, deviceName=ANY

**Comment by vdelendik** [comment]
Need to declare cases for job types:
android-web
ios-web

**Comment by vdelendik** [comment]
@okamara, all changes delivered. Testing can be done using QPS_PIPELINE_BRANCH: master

**Comment by okamara** [comment]
Tested. Fixed.

**Comment by okamara** [comment]
Verified
