### ISSUE TITLE
adjust jenkinsDefaultThreadCount usage based on carina changes

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#524]
details: https://github.com/qaprosoft/carina/issues/859
maybe it has sense to remove "jenkinsDefaultThreadCount" custom argument at all and reuse value from suite declaration header:
suite name="Parallel test suite" parallel="methods" thread-count="2"

that's should be enough for our JobDSL to adjust default thread count values

**Comment by vdelendik** [comment]
it should be fixed after https://github.com/qaprosoft/carina/issues/859

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/606

**Comment by okamara** [comment]
In the case when data-provider-thread-count="10" "0" is ignored in job value.
<img width="530" alt="Screen Shot 2020-01-16 at 2 25 12 PM" src="https://user-images.githubusercontent.com/32964663/72521772-2580a500-386d-11ea-963b-912f3005a0fc.png">
<img width="991" alt="Screen Shot 2020-01-16 at 2 31 55 PM" src="https://user-images.githubusercontent.com/32964663/72521780-29142c00-386d-11ea-92e5-0cf8fcd41d19.png">

**Comment by vdelendik** [comment]
need to retest after merging into the develop

**Comment by vdelendik** [comment]
@okamara @dhreben please test using latest versions from develop

**Comment by okamara** [comment]
Retested. Done.
