### ISSUE TITLE
add extra verification for suiteOwner value

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#525]
let's do analysis of the suiteOwner vallue for comma sign. If it present we should 
1) split by comma
2) use first name before comma sign
3) put error message that "multiply ownership is impossible" 
ideally continue scan till the end and assert at the end like soft assert do

**Comment by okamara** [comment]
Verified 1,2 points and 3 is skipped.

**Comment by ilya-varchenya** [comment]
#552
