### ISSUE TITLE
[onPullRequest-carina-demo-trigger/githubCredentials]

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-pipeline#530]
No instructions that admin credentials should be set up.
admin credentials is not installed by default in Credentials.

<img width="1134" alt="Screen Shot 2019-11-25 at 5 02 29 PM" src="https://user-images.githubusercontent.com/32964663/69546768-695dd900-0fa5-11ea-82d0-a763913fe612.png">

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/qps-infra/blob/master/docs/getting_started.md

![image](https://user-images.githubusercontent.com/4551455/76024638-8444cf80-5f3c-11ea-811b-a01e73c01b9a.png)

**Comment by okamara** [comment]
Verified
