### ISSUE TITLE
support space as part of zafiraFields argument value

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#531]

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/532

**Comment by okamara** [comment]
@vdelendik what fields do you mean in this ticket?

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/578

**Comment by okamara** [comment]
Testing is blocked with https://github.com/qaprosoft/zafira/issues/1977

**Comment by okamara** [comment]
Verified on develop branch. Fixed.
