### ISSUE TITLE
Change instruction link to Install docker(Ubuntu) for newer version 

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-pipeline#545]
Open https://github.com/qaprosoft/qps-infra
Go to  Install docker(Ubuntu ) instruction
Change instruction link for Ubuntu (see image) from https://www.techrepublic.com/article/how-to-install-docker-on-ubuntu-16-04/  to https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04  

<img width="1185" alt="Screen Shot 2019-12-04 at 5 40 38 PM" src="https://user-images.githubusercontent.com/32964663/70151976-6b1e4f80-16bd-11ea-8cd3-44bd60babcb5.png">

**Comment by vdelendik** [comment]
done: https://github.com/qaprosoft/qps-infra/commit/da53d229613896cac52b29dfec25f1263212568a

**Comment by okamara** [comment]
Now the structure of the instruction is changed.
New link https://github.com/qaprosoft/qps-infra/blob/master/docs/getting_started.md
