### ISSUE TITLE
remove any reference onto the gc_GIT_BRANCH from pipeline code and docs

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#556]
all branch values should be registered as textfield with default value without any reference onto the global choice list.
As only jobdsl and pipeline updated we have to remove it's declaration for jenkins-master

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/558

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/560

**Comment by vdelendik** [comment]
@okamara, testing scenario:
1) remove in "manage jenkins->configure system" gc_GIT_BRANCH
2) register organization and repo from scratch using master branch
-> Verify that
 - all test jobs should be created
 - parameter "branch" for all jobs should be regular text field with default value: master

3) Remove repositories and organization
4) re-register again for carina-demo but using any non default branch
-> Verify that
 - onPush job was executed based on custom branch
 - all test jobs should have branch: custom value
 - executing jobs by default are triggered from valid custom branch

5) re-scan repository again using master branch
-> Verify that
 - onPush job was executed based on master branch
 - all test jobs should have branch: master value
 - executing jobs by default are triggered from master branch by default

6) run any job updating default branch value onto another one

**Comment by okamara** [comment]
For case in step 4:
Carina-Demo-Regression-Pipeline
  branch = my folder name instead of custom branch

CutBranch-carina-demo
  branch = master instead of custom branch

no branch for onPullRequest-carina-demo

@vdelendik is it expected for this case?

**Comment by okamara** [comment]
For case 6 previous branch value is not updated in config, run api job.:
<img width="445" alt="Screen Shot 2019-12-12 at 5 58 55 PM" src="https://user-images.githubusercontent.com/32964663/70722971-350a4c80-1d09-11ea-898c-6beab7f26737.png">

<img width="640" alt="Screen Shot 2019-12-12 at 5 59 20 PM" src="https://user-images.githubusercontent.com/32964663/70722991-3b98c400-1d09-11ea-860d-6b4b3f28a9b5.png">

**Comment by okamara** [comment]
Reverified after the latest fix from Vadim
