### ISSUE TITLE
speedup cloning process adding adjusted refspec 

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#563]
provide single branch refspec for cloning: "+refs/heads/${branch}:refs/remotes/origin/${branch}"

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/qps-pipeline/commit/e98344e0b068a2665d76eca697fcf341c006f20e

**Comment by vdelendik** [comment]
backported to 4.8 as well

**Comment by okamara** [comment]
Verified
