### ISSUE TITLE
inspect default maven goals and remove duplicates

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#564]
need to review all default goals we generate from QARunner and extra global vars:
https://github.com/qaprosoft/qps-pipeline/blob/e98344e0b068a2665d76eca697fcf341c006f20e/src/com/qaprosoft/jenkins/pipeline/runner/maven/QARunner.groovy#L784

after that we should organize it in such way that there is no duplicates in the same command line removing already inserted/parsed values from Configuration array etc

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/577

**Comment by okamara** [comment]
Verified. Fixed.
