### ISSUE TITLE
Specify job_type value in cron job.

### ISSUE THREAD

**Issue by kolyakrasnik** [qaprosoft/qps-pipeline#570]
Currently job_type value is not populated in cron jobs. So, during execution with pipeline 4.8 script can't determine which one project has beed triggered. Job_type value affect logic for selenium_hub property population.

**Comment by vdelendik** [comment]
@kolyakrasnik, is it still actual or we could remove it correctly in 4.8 milestone from cron jobs

**Comment by vdelendik** [comment]
closing as not actual anymore for cron jobs
