### ISSUE TITLE
parse capabilities field on pipeline level and don't register it and it's value in launchers

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#582]
For launchers we are interested only for platformName, deviceName, browserName and browserVersion.
if we find this values from "capabilities" field we can register them in launchers. default capabilities field and value shouldn't be registered in Zafira

**Comment by ilya-varchenya** [comment]
#596

**Comment by ilya-varchenya** [comment]
@okamara
You need to add parameter to any .xml job-file in your carina-demo test branch:
'<parameter name="capabilities" value="browserName=" />'
So you should see something like that in logs of onPush job
![image](https://user-images.githubusercontent.com/44428408/71746938-5fba7180-2e7f-11ea-805c-8554f5a4c791.png)

**Comment by okamara** [comment]
Verified
