### ISSUE TITLE
investigate can we delete "browser" and "browser_version" from code

### ISSUE THREAD

**Issue by ilya-varchenya** [qaprosoft/qps-pipeline#583]
We should investigate can we delete "browser" and "browser_version" from code qps-pipeline or we need to make some handler stuff for that parameters

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/qps-pipeline/commit/ebeefee13ef7281e20ced0cdf1beabe3dd09ab1c
https://github.com/qaprosoft/qps-pipeline/commit/9c16f42f4d60825320e7b26f9a8a563f8a17c12d
https://github.com/qaprosoft/qps-pipeline/commit/8a26542dcdad80a676e9c62865be6adaac2baee7

**Comment by okamara** [comment]
Fixed.
