### ISSUE TITLE
regression: unable to start pipeline cron for different browsers config matrix

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#586]
to setup custom test matrix for cron pipelines we use:
	parameter name="jenkinsPipelineBrowsers" value="browser: chrome; browser: firefox"/

later cron job statr children jobs using old "browser" parameter.
We have to investigate if it is possible to fix keeping old notation or inform everyone to change jenkinsPipelineBrowsers parameter (maybe "jenkinsPipelineCapabilities")

**Comment by vdelendik** [comment]
old crons like "http://demo.qaprosoft.com/jenkins/job/carina-demo/job/Carina-Demo-Regression-Pipeline/" still could provide argument via "browser: firefox".
Adjusted pipeline code to support those notation as well because migration becomes super complicated without this code

**Comment by okamara** [comment]
Fixed.
