### ISSUE TITLE
remove initJobParams from QARunner

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#587]
protected def initJobParams() {
		//TODO: test this removal
//        if (isParamEmpty(Configuration.get("platform"))) {
//            Configuration.set("platform", "*") //init default platform for launcher
//        }
        if (isParamEmpty(Configuration.get("browser"))) {
            Configuration.set("browser", "NULL") //init default platform for launcher
        }
    }

2nd if operator also looks obsolete so let's scan known private pipeline libraries and remove this method

**Comment by okamara** [comment]
@vdelendik could you please add details how to check this bug?

**Comment by okamara** [comment]
To test:
Run pipeline job
Run separate Web and Api jobs
Fixed.
