### ISSUE TITLE
Add "Warning" for invalid "capabilities" field in logs

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-pipeline#597]
Add "Warning" for invalid "capabilities" field in logs for carina-demo

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/598
![image](https://user-images.githubusercontent.com/44428408/71804560-e1272500-3074-11ea-8616-5fcc89f6e225.png)

**Comment by okamara** [comment]
Verified
![Uploading Screen Shot 2020-01-08 at 1.52.34 PM.png…]()

**Comment by okamara** [comment]
<img width="563" alt="Screen Shot 2020-01-14 at 1 56 15 PM" src="https://user-images.githubusercontent.com/32964663/72340810-e110d000-36d9-11ea-9de5-3f91bb25ac4f.png">
