### ISSUE TITLE
remove useless testng grabbing

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#602]
test possibility to remove those line: @Grab('org.testng:testng:6.8.8')

From:
LauncherJobFactory.groovy
RegisterRepositoryJobFactory.groovy

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/603

**Comment by ilya-varchenya** [comment]
@okamara, please check this ticket in our classic flow

**Comment by okamara** [comment]
Verified.
