### ISSUE TITLE
"onPullRequest" job is triggered and run successfully without adding write permissions in "GitHub Pull Request Builder"

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-pipeline#604]
Description:
**"onPullRequest" job is triggered and run successfully without adding write permissions in "GitHub Pull Request Builder"**

Steps:
1. In manage Jenkins skip configuration "GitHub Pull Request Builder"
2. Stop/Start Pull request via git
3. Verify that "onPullRequest" jobs are run with errors and show red color
Actual result:  "onPullRequest" jobs are triggered and show blue color

**Comment by ilya-varchenya** [comment]
Close because it hasn't repeated
