### ISSUE TITLE
possibility to see Test account details (email/password) where test is run in Testtrail results

### ISSUE THREAD

**Issue by NadiMarkava** [qaprosoft/qps-pipeline#605]
Testrail-updater is able to show the link on test run in comment, need to add test account details from test that will be shown in comment too
<img width="584" alt="Screen Shot 2020-01-14 at 12 04 51 PM" src="https://user-images.githubusercontent.com/38868848/72344875-68167600-36e3-11ea-81db-257652cb7bd8.png">

**Comment by vdelendik** [comment]
it is closed with won't fix resolution as result is not so useful in comparison with required work
