### ISSUE TITLE
.m2 folder couldn't be used after clearing it

### ISSUE THREAD

**Issue by ilya-varchenya** [qaprosoft/qps-pipeline#607]
![image](https://user-images.githubusercontent.com/44428408/72517847-257ca700-3865-11ea-976d-a94bc42c44fb.png)

**Comment by vdelendik** [comment]
$HOME/.m2 is not shared anymore into jenkins (neither slave nor master)
So you can remove it on the Linux host without affecting the jobs

**Comment by okamara** [comment]
Fixed.
