### ISSUE TITLE
When data-provider-thread-count="10" "0" is ignored in job value

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-pipeline#608]
Steps:
1. Open xml file e.g. android.xml in your test repo from git 
2. Set data-provider-thread-count="10" thread-count="10" in <suite name="Carina Demo Tests - Mobile Sample (Android)" verbose="1" skipfailedinvocationcounts="false" junit="false" parallel="methods" data-provider-thread-count="10" thread-count="10" annotations="JDK">
3. In jenkins Register repo carina-demo for test branch with changes in android.xml
4. Open carina-demo/android.xml and tab Build with parameters
5. Verify that data-provider-thread-count="10"
Actual result:data-provider-thread-count="1" (issue only for value 10 it works fine for 22 or 2)
<img width="991" alt="Screen Shot 2020-01-16 at 2 31 55 PM" src="https://user-images.githubusercontent.com/32964663/72523051-0a636480-3870-11ea-8116-299918182f01.png">
<img width="530" alt="Screen Shot 2020-01-16 at 2 25 12 PM" src="https://user-images.githubusercontent.com/32964663/72523061-0cc5be80-3870-11ea-994a-6083e4b9bff5.png">

**Comment by vdelendik** [comment]
we have to take a look onto the parse implementation in carina: https://github.com/qaprosoft/carina/pull/980

**Comment by ilya-varchenya** [comment]
![image](https://user-images.githubusercontent.com/44428408/79850257-4dcbf280-83cc-11ea-82a0-cb688c3284af.png)

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/709

**Comment by vdelendik** [comment]
@okamara, changes merged to develop branch.
during a scan we parse thread-count and data-provider-thread-count only from suite tag in ech test xml file. For example:
https://github.com/qaprosoft/carina-demo/blob/488bc303c16bf1d178be45d2d0c81955d9bc72b4/src/test/resources/testng_suites/api.xml#L2
https://github.com/qaprosoft/carina-demo/blob/488bc303c16bf1d178be45d2d0c81955d9bc72b4/src/test/resources/testng_suites/regression/dataprovider-retry.xml#L2

feel free to play with those numbers in your test carina-demo branches.
By default if not thread-count detected we should generate for the job: thread-count=1
if no data-provider-thread-count declared in suite - no data_provider_thread_count field.

Any custom value presented in suite xml should appear in appropriate fields on the job after scan

**Comment by okamara** [comment]
In the case -> <suite verbose="1" name="Carina Demo Tests - Web Single Driver Sample" parallel="tests" data-provider-thread-count="1" thread-count="5">   
Actual result: In job config -> thread-count="5" , no  data-provider-thread-count
Expected:  In job config -> data-provider-thread-count="1" thread-count="5"
