### ISSUE TITLE
timestamper calls plugin wasn't removed from pipeline groovy scripts

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#609]
Unable to do any management etc job as we have 
                    context.timestamps {
...

so if we want to remove it we have to remove above lines as well. Let's comment so far and test that org/repo are registered and jobs are executed successfully. 

@ilya-varchenya Let's organize in such way:
1) keep timestamper installed 
2) comment "context.timestamps {" calls across all groovy scripts
-> test performance of full console log output

If confirmed that performance issue is  fixed let's return it into the list of plugin for manual deployment

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/compare/master...timestmp?expand=1

**Comment by vdelendik** [comment]
verifid on my onw
