### ISSUE TITLE
Matrix with updated retry count params doesn’t work(shows wrong retry count param's name and value)

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-pipeline#620]
Matrix with updated retry count params doesn’t work(shows wrong retry count param's name and value)

**Comment by vdelendik** [comment]
1) fixed matrix args in carina-demo
https://github.com/qaprosoft/carina-demo/commit/149897ad2c75e471e84b736ed1e543e26ac7dd33

2) supported use-case with overriding default args like retry_count as well:
https://github.com/qaprosoft/qps-pipeline/commit/50cea7ea67efef502cc5f1c42de2226d1650d18d
