### ISSUE TITLE
Email list job parameter is duplicated

### ISSUE THREAD

**Issue by Boniara** [qaprosoft/qps-pipeline#627]
We can see email_list and emailList in one scope of job parameters.
'emailList' appears when 'jenkinsEmail' property is present in xml suite.
Zafira issue reference: https://github.com/qaprosoft/zafira/issues/1990

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/636

**Comment by dhreben** [comment]
Verified. Fixed.
