### ISSUE TITLE
identify all pipeline code related to SELENIUM_* and remove it

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#631]
Configuration.groovy
        SELENIUM_PROTOCOL("SELENIUM_PROTOCOL", "http"),
        SELENIUM_HOST("SELENIUM_HOST", "\${QPS_HOST}"),
        SELENIUM_PORT("SELENIUM_PORT", "4444"),
        SELENIUM_URL("SELENIUM_URL", "\${SELENIUM_PROTOCOL}://demo:demo@\${SELENIUM_HOST}:\${SELENIUM_PORT}/wd/hub"),

**Comment by vdelendik** [comment]
@okamara changes are available in 4.10.2 qps-pipeline branch.
Attention new 4.10.2 jenkins-master should be released soon as well to update several management_jobs

test scenario for empty and non-empty organization is pretty simple :
1) run Web-Demo-Test 
2) inside logs by default there should be below value with your ip instead if demo.qaprosoft.com
selenium_host=http://demo:demo@demo.qaprosoft.com/ggr/wd/hub

**Comment by okamara** [comment]
Verified. Done.

**Comment by okamara** [comment]
I see 2 type of urls -> http://demo:demo@ip/ggr/wd/hub   or http://demo:********@ip/ggr/wd/hub
