### ISSUE TITLE
don't declare custom_capabilities field in each test job if gc_CUSTOM_CAPABILITIES is empty

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#634]
such field shouldn't be created if it has only NULL values
![image](https://user-images.githubusercontent.com/4551455/74788240-3f753380-52c2-11ea-8199-9cdf09e8ede1.png)

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/635

**Comment by okamara** [comment]
Verified. Fixed.
