### ISSUE TITLE
improve jobdsl for env choice parameters

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#638]
To don't limit env by choiceParam values only let's review our JobDSL logic and replace choiceParam for env by extensible choices.
Important note: editable checkbox must be picked!
![image](https://user-images.githubusercontent.com/4551455/75538106-24749300-5a29-11ea-89ed-fed5a9f1bdac.png)

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/640

**Comment by ilya-varchenya** [comment]
We must check that there're could be more than one parameter

**Comment by ilya-varchenya** [comment]
@dhreben, you should update any job.xml file with more than one parameter
**<parameter name="jenkinsEnvironments" value="PROD,STAG"/>**
'env' parameter must have DEMO and STAG parameters, when there's no jenkinsEnviroments parameter in xml file at all, or jenkinsEnviroments parameter is empty

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/640

**Comment by okamara** [comment]
@ilya-varchenya what is expected result for the following cases?

Case:
In the case when we delete Demo and write param -> parameter name="jenkinsPipelineEnvironments" value="PROD, DEV"
Actual result: DEMO STAG PROD appears in Configure

Case:
In the case when we delete Demo param from nightly regression in Web.xml
Actual result: we see default DEMO param in Configure

Case:
In the case when we delete Demo param from nightly regression in api.xml and write param ->
parameter name="jenkinsEnvironments" value="DEMO"
parameter name="jenkinsEnvironments" value="Test1"
Actual result: we see Test1 value in param in Configure

**Comment by ilya-varchenya** [comment]
@okamara, @dhreben and I check all cases according to updates in PR. So everything is expectable
