### ISSUE TITLE
Disabled zafira shouldn't fail a build

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#644]
We have to review zafira integration having an ability to disable it via one attribute. 
When integration is disabled we shouldn't do any call to it to not affect build status

**Comment by vdelendik** [comment]
@okamara 
https://github.com/qaprosoft/qps-pipeline/pull/662
changes are available in branch: zfr-disable

1. During organization registration you can provide zafira url and token
-> if yes, all repositories will try to use them for tests results registration
-> if no - only CarinaReport, and two TestNG reports could be published

2. Also make sure to verify use-case and let me know the results when url and token provided but during execution zafira is inaccessible

3. CarinaReport emailable report should be published obligatory in any case

4. For disabled Zafira integration job status should be positive when no errors detected among tests

**Comment by okamara** [comment]
Need more details for testing this ticket.

**Comment by okamara** [comment]
Verified.
