### ISSUE TITLE
remove onPush configuration steps from onPullRequest-repo job

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#652]
There is copy-paste from onPush job:
http://demo.qaprosoft.com/jenkins/job/qaprosoft/job/carina-demo/view/SYSTEM/job/onPullRequest-carina-demo/

please remove configuration step fromonPullRequest-repo! Maybe add short description like:
Verify compilation and/or do Sonar PullRequest analysis is possible

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/658

**Comment by ilya-varchenya** [comment]
@okamara or @dhreben, check this ticket with the next steps:
1. Go to Jenkins
2. Change qps-pipelines branch to an appropriate one
3. Register organisation
4. Register repository with
5. Check that description of onPullRequest job was changed

**Comment by okamara** [comment]
Fixed.
