### ISSUE TITLE
Update replaceSlashes() method

### ISSUE THREAD

**Issue by ilya-varchenya** [qaprosoft/qps-pipeline#654]
https://github.com/qaprosoft/qps-pipeline/pull/653/files#diff-185b27bd49ffa218296e808cf2f5781fR44
Rename this method to replaceSpecialSymbols() and add more special symbols ":", "|"

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/657

**Comment by ilya-varchenya** [comment]
@dhreben or @okamara, check this ticket with next steps:
1. Update jenkinsJobName parameter in any your_repo/carina-demo test job with special symbols
It should look like that: _<parameter name="jenkinsJobName" value="API-Demo-Test:1111/2222|3333"/>_
2. Go to Jenkins
2.1 Change qps-pipelines branch to an appropriate one
2.2 Register organisation
2.3 Register repository with an appropriate carina-demo branch
3. Check that name of updated job will change

All special symbols must change to "_" symbol. So according to step **1** it should be like that: **API_Demo_Test_1111_2222_3333**

**Comment by okamara** [comment]
Register repository is Failure. Test with <parameter name="jenkinsJobName" value="Web-Demo-Test:1111/2222|3333"/>

**Comment by ilya-varchenya** [comment]
@okamara check pipelines branch

**Comment by okamara** [comment]
I used develop. Wha branch I need to use?

**Comment by okamara** [comment]
Verified. Fixed.
