### ISSUE TITLE
zafiraServiceURL and zafiraAccessToken is empty for RegisterOrganization

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-pipeline#664]
Steps:
1. Start Jinkins
2. open Create organization page
3. Verify that zafiraServiceURL and zafiraAccessToken has default values 
Actual result:zafiraServiceURL and zafiraAccessToken is empty field

<img width="726" alt="Screen Shot 2020-03-23 at 2 41 32 PM" src="https://user-images.githubusercontent.com/32964663/77316574-b450e880-6d1a-11ea-86e7-011b96b1f4ec.png">

**Comment by ilya-varchenya** [comment]
Created ticket in an appropriate repo: https://github.com/qaprosoft/jenkins-master/issues/150

**Comment by ilya-varchenya** [comment]
qa-verified in an appropriate repo
