### ISSUE TITLE
Delete no more need parameter from replaceSpecialSymbols()

### ISSUE THREAD

**Issue by ilya-varchenya** [qaprosoft/qps-pipeline#665]
Update replaceSpecialSymbols()
It should get only one parameter
**static def replaceSpecialSymbols(String value)**

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/666

**Comment by ilya-varchenya** [comment]
@okamara and @dhreben, please verify this ticket with the scenario of https://github.com/qaprosoft/qps-pipeline/issues/654

**Comment by ilya-varchenya** [comment]
Please, try to run some regression job and read it's logs. It could be successful, but check that test-jobs were started.
Maybe we need to create appropriate issue

**Comment by ilya-varchenya** [comment]
New issue was created: https://github.com/qaprosoft/qps-pipeline/issues/667

**Comment by okamara** [comment]
Fixed.
