### ISSUE TITLE
improve artifacts uploading to the CI

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#668]
![image](https://user-images.githubusercontent.com/4551455/77372296-771a4400-6d76-11ea-868b-fb544b2712fe.png)

1. Let's try to use valid file names to publish them as artifact to jenkins build
2. let's skip uploading of the *.mp4 video files as artifacts (in new carina they will appear there)

**Comment by okamara** [comment]
@vdelendik or @ilya-varchenya could you please add more details for verification this ticket?

**Comment by okamara** [comment]
<img width="275" alt="Screen Shot 2020-04-02 at 11 43 38 AM" src="https://user-images.githubusercontent.com/32964663/78228346-40ab9a00-74d7-11ea-953a-cc0dd36f259e.png">
Verified.
