### ISSUE TITLE
don't start test if integrated zafira is down or unavailable

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-pipeline#669]
During organization registration you can provide zafira url and token
-> if no - don't start test if integrated zafira is down or unavailable

**Comment by vdelendik** [comment]
@okamara fixed: https://github.com/qaprosoft/qps-pipeline/issues/669
when organization is registered with non empty zafira properties we raise such exception and stop script when during launch zafira is inaccessible: 
Unable to get auth token, check Zafira integration!

**Comment by okamara** [comment]
onPush Job is not started when Zafira is stopped.
