### ISSUE TITLE
Investigate maven runner behavior when zafira becomes inaccessible during the test execution

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-pipeline#670]

**Comment by vdelendik** [comment]
TBD what to do in this case with interested bodies

**Comment by vdelendik** [comment]
In 5.0 test is executed till the end but a lot of exceptions in logs about errors with registering tests.
CarinaReport is published. So from pipeline point of view everything is good, maybe we should improve carina/zafira-client to abort execution asap if zafira becomes inaccessible in a middle

00:26:08  2020-05-13 21:26:04 com.qaprosoft.zafira.util.http.HttpClient$Executor [TestNG-tests-1] [ERROR]: java.net.NoRouteToHostException: Host is unreachable (Host unreachable). Unable to finish test
00:26:08  com.sun.jersey.api.client.ClientHandlerException: java.net.NoRouteToHostException: Host is unreachable (Host unreachable)
00:26:08  	at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:155)
00:26:08  	at com.sun.jersey.api.client.Client.handle(Client.java:652)
00:26:08  	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
00:26:08  	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
00:26:08  	at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570)
00:26:08  	at com.qaprosoft.zafira.util.http.HttpClient$Executor.lambda$post$1(HttpClient.java:85)
00:26:08  	at com.qaprosoft.zafira.util.http.HttpClient$Executor.execute(HttpClient.java:127)
00:26:08  	at com.qaprosoft.zafira.util.http.HttpClient$Executor.post(HttpClient.java:85)
00:26:08  	at com.qaprosoft.zafira.client.impl.BasicClientImpl.finishTest(BasicClientImpl.java:224)
00:26:08  	at com.qaprosoft.zafira.client.impl.ZafiraClientImpl.finishTest(ZafiraClientImpl.java:139)
00:26:08  	at com.qaprosoft.zafira.listener.service.impl.TestTypeServiceImpl.finishTest(TestTypeServiceImpl.java:73)
00:26:08  	at com.qaprosoft.zafira.listener.ZafiraEventRegistrar.finishTest(ZafiraEventRegistrar.java:607)
00:26:08  	at com.qaprosoft.zafira.listener.ZafiraEventRegistrar.onTestSuccess(ZafiraEventRegistrar.java:313)
00:26:08  	at com.qaprosoft.zafira.listener.ZebrunnerListener.onTestSuccess(ZebrunnerListener.java:48)
00:26:08  	at com.nordstrom.automation.testng.ListenerChain.onTestSuccess(ListenerChain.java:379)
00:26:08  	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:70)
00:26:08  	at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
00:26:08  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:651)
00:26:08  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
00:26:08  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
00:26:08  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
00:26:08  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
00:26:08  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
00:26:08  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
00:26:08  	at java.util.ArrayList.forEach(ArrayList.java:1257)
00:26:08  	at org.testng.TestRunner.privateRun(TestRunner.java:766)
00:26:08  	at org.testng.TestRunner.run(TestRunner.java:587)
00:26:08  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
00:26:08  	at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
00:26:08  	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
00:26:08  	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
00:26:08  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:26:08  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
00:26:08  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
00:26:08  	at java.lang.Thread.run(Thread.java:748)

[consoleText.log](https://github.com/qaprosoft/qps-pipeline/files/4624764/consoleText.log)

**Comment by vdelendik** [comment]
won't fix as too many components are involved. infra should be stable to work properly
