### ISSUE TITLE
Unable to register Zafira credentials. Required fields are missing

### ISSUE THREAD

**Issue by dhreben** [qaprosoft/qps-pipeline#675]
Steps:
1.Tap Management_Jobs
2.Tap RegisterOrganization
3.Tap Build with Parameters
4.Folder name is empty
5.Tap Build
6.Open Console Output
      
 Actual result:  Unable to register Zafira credentials. Required fields are missing

![image](https://user-images.githubusercontent.com/50950954/78449896-447c1f80-7683-11ea-89cb-adc80bc7ea2a.png)

**Comment by ilya-varchenya** [comment]
The main reason of that bug, that now it has not folderName parameter (it's null). So, we have such exception message

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/676

**Comment by dhreben** [comment]
Fixed.
