### ISSUE TITLE
Need to update handling of empty organisation's name fields

### ISSUE THREAD

**Issue by ilya-varchenya** [qaprosoft/qps-pipeline#678]
Investigate where does it need
Check RegisterHubCredentials job and check QARunner's method updateSeleniumUrl

P.S. Here we need to use value from GITHUB_ORGANIZATION if folderName is empty

**Comment by vdelendik** [comment]
PR: https://github.com/qaprosoft/qps-pipeline/pull/679

@okamara, tests scenario variant#1:
1) sudo ./clear.sh
2) update qps-pipeline branch in jenkins to "develop"
3) RegisterOrganization with empty folderName
4) run from root RegisterRepository
5) execute /carina-demo/nightly_regression cron
-> all api and web tests run as usual

 variant#2:
1) sudo ./clear.sh
2) update qps-pipeline branch in jenkins to "develop"
3) RegisterOrganization with folderName="qaprosoft"
4) run from root /qaprosoft/RegisterRepository
5) execute /qaprosoft/carina-demo/nightly_regression cron
-> all api and web tests run as usual

**Comment by vdelendik** [comment]
verified on real env
