### ISSUE TITLE
replaceSpecialSymbols should ignore "-"

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#682]
too many new jobs created if we replace "-" by "_" and we lose a lot of valuable statistics.
Need apply hot fix and keep "-" symbol as is for job and cron names

**Comment by vdelendik** [comment]
fixed: https://github.com/qaprosoft/qps-pipeline/commit/65a66624232235497beb5036827ace53d85c0b82

**Comment by okamara** [comment]
Verified.
