### ISSUE TITLE
testcase management integration still uses global vars: zafira_service_url and zafira_access_token

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#690]
we tried to avoid using zafira_service_url and zafira_access_token from global env variables.
but either qtest so testrail integration clients still use default ZafiraClient with those vars. Need to refactor integration and use appropriate values based on organization value

**Comment by vdelendik** [comment]
too many changes so moved to 4.10.2.
Fixes are here: https://github.com/qaprosoft/qps-pipeline/pull/695

**Comment by vdelendik** [comment]
@okamara too many changes so regular regression better to execute using qps-pipeline-branch: 4.10.2

**Comment by okamara** [comment]
Regular regression is done.

**Comment by dhreben** [comment]
fixed
