### ISSUE TITLE
secure maven console output excluding GITHUB_OAUTH_TOKEN tokan as plain text

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#702]
qps-pipeline\src\com\qaprosoft\jenkins\pipeline\tools\maven\sonar\Sonar.groovy
Executing executeMavenGoals for executeSonarPRScan and executeSonarFullScan shows in plain text sonar.github.oauth
Need to double check and exclude from out put secured information. In that case it is about GITHUB_OAUTH_TOKEN env var 

mvn -B -U -f pom.xml clean compile test-compile package sonar:sonar -DskipTests=true -Dsonar.github.endpoint=https://api.github.com/ -Dsonar.analysis.mode=preview -Dsonar.github.pullRequest=NNNN -Dsonar.github.repository=qaprosoft/carina-demo -Dsonar.projectKey=carina-demo-Dsonar.projectName=carina-demo -Dsonar.projectVersion=1.1960 -Dsonar.github.oauth=PLAINTEXT_TOKEN -Dsonar.sources=. -Dsonar.tests=. -Dsonar.inclusions=**/src/main/java/** -Dsonar.test.inclusions=**/src/test/java/** -Dsonar.java.source=1.8

**Comment by ilya-varchenya** [comment]
@vdelendik, did you mean that GITHUB_OAUTH_TOKEN must be unsecured?

**Comment by ilya-varchenya** [comment]
Like that:
https://github.com/qaprosoft/qps-pipeline/pull/736/files

**Comment by vdelendik** [comment]
@ilya-varchenya, nope. already discussed in private requirements

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/744
https://github.com/qaprosoft/jenkins-master/pull/223

**Comment by okamara** [comment]
Done

**Comment by okamara** [comment]
Need to complete testing.

**Comment by okamara** [comment]
sonarGithubOAuth  is added to Register organization
