### ISSUE TITLE
BLOCKER: there is no default value for env extensible choice

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#705]
http://demo.qaprosoft.com/jenkins/job/qaprosoft/job/carina-demo/job/Web-Demo-Test/configure

default value for the env should be 1st one from drop down! For now it is a blocker because jobs started by timer have env="" and crach

![image](https://user-images.githubusercontent.com/4551455/79733772-4a6a3580-82fe-11ea-82b5-c35fb4ff2694.png)

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/706

**Comment by ilya-varchenya** [comment]
@okamara and @dhreben, please, verify this ticket with job from master branch of carina-demo and custom branch where web.xml doesn't contains jenkinsEnvironments parameter. 
Parameter configuration must looks like on a picture
![image](https://user-images.githubusercontent.com/44428408/79741509-0d0ba500-830a-11ea-9729-c891f049cb48.png)

**Comment by okamara** [comment]
<img width="655" alt="Screen Shot 2020-04-20 at 10 03 16 PM" src="https://user-images.githubusercontent.com/32964663/79789396-c7bf9580-8352-11ea-9d7b-283566174a98.png">
When I remove jenkinsEnvironments parameter from Job default value is Top Most Value and user need to set value to e.g. "DEMO"

**Comment by okamara** [comment]
<img width="637" alt="Screen Shot 2020-04-20 at 10 18 18 PM" src="https://user-images.githubusercontent.com/32964663/79790920-284fd200-8355-11ea-9d46-cd1aa77eeea9.png">
- job from master branch of carina-demo

**Comment by okamara** [comment]
Verified  on branch 4.10.3 :
1. Custom branch
<img width="646" alt="Screen Shot 2020-04-20 at 11 37 58 PM" src="https://user-images.githubusercontent.com/32964663/79797525-1162ad00-8360-11ea-9b37-6dd5e35a4957.png">

**Comment by okamara** [comment]
2.
![Uploading Screen Shot 2020-04-21 at 12.03.54 AM.png…]()
