### ISSUE TITLE
Add parameter for disabling of concurent runs for the job

### ISSUE THREAD

**Issue by SergeiZagriychuk** [qaprosoft/qps-pipeline#708]
By default jobs generated by qps-pipeline can be executed concurrently by several parallel triggers.
At some projects it's reasonable to disable concurrent runs not to interrupt runs by each other.
Please introduce new suite parameter which will disable such concurrency. Not to change existent flow set it to false by default.
Note: in Jenkins job config parameter "Do not allow concurrent builds" handles this

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/759

**Comment by ilya-varchenya** [comment]
@okamara @dhreben 
Add `<parameter name="disableConcurrentBuild" value="true"/> `into suite .xml file
If this parameter = true, parameter on a picture must be ticked
![image](https://user-images.githubusercontent.com/44428408/82449108-60147b80-9ab3-11ea-9d8e-032f0094eee3.png)

**Comment by okamara** [comment]
Could not check this ticket as faced with issue https://github.com/qaprosoft/qps-pipeline/issues/761

**Comment by okamara** [comment]
Tested. Fixed.
