### ISSUE TITLE
Warning: Credential ID qaprosoft is null could not be found appears in Job console log

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-pipeline#710]
Warning: Credential ID qaprosoft is null could not be found appears in Job console log if Folder is created with empty name, and repository created with default name.

<img width="1034" alt="Screen Shot 2020-04-20 at 9 18 25 PM" src="https://user-images.githubusercontent.com/32964663/79862773-44985100-83df-11ea-92cc-82380c1b76c7.png">

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/714

**Comment by okamara** [comment]
Still repro on qps-pipeline = develop.

**Comment by okamara** [comment]
steps:
1. Create organization with empty name
2. Register repository with default name
Open Console log and verify warning message is present or not
