### ISSUE TITLE
Rename old zafiraServiceUrl and zafiraAccessToken fields and vars

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#715]
Together with changing job fields let's rename correctly on qps-pipeline internal variables for that.
https://github.com/qaprosoft/jenkins-master/issues/204

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/720

**Comment by okamara** [comment]
Fixed.
