### ISSUE TITLE
Rerun failed tests doesn't work as expected

### ISSUE THREAD

**Issue by mverkhautsova** [qaprosoft/qps-pipeline#719]
**Description**
User has test run with failed tests. After tapping on rerun only failures all tests rerun. 
https://github.com/zebrunner/zebrunner/issues/2131

**Steps to reproduce**

1. Go to list with test builds.
2. Select failed test build. Click rebuild. Select rerun_failures.

**Actual behavior**
All tests rerun.

**Expected behavior**
Only failed tests rerun.

**Environment**
4.10 (2020-04-14)

**Comment by vdelendik** [comment]
issue in zafira-client localized and fixed.
Fix will be available in 6.5.36+
