### ISSUE TITLE
integration with zafira is broken for test execution

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#721]
unbale to register test run in zafira due to the invalid -Dzafira_service_url parameter:
http://demo.qaprosoft.com/jenkins/job/qaprosoft/job/carina-demo/job/API-Demo-Test/1/console

Logs:
mvn -B -U -Dselenium_host=http://demo:********@demo.qaprosoft.com/ggr/wd/hub -Dmaven.test.failure.ignore=true -Dzafira_enabled=true **-Dzafira_service_url={must_override}** -Dzafira_access_token=********

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/211
