### ISSUE TITLE
remove any reference to ggr

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#723]
in 5.0 starter kit only selenoid will be used with possibility to auto-update browser.
need scan all pipeline sources and change ggr->selenoid urls if any

**Comment by vdelendik** [comment]
done: https://github.com/qaprosoft/qps-pipeline/commit/e6f763e544be20f42f3ceeb0fc4eb67c34e0d453

**Comment by vdelendik** [comment]
@okamara test scenario:
1) review all files in qps-pipeline: develop
-> no "ggr" word present at all
2) after default setup web tests can be executed successfully

**Comment by okamara** [comment]
Fixed.
