### ISSUE TITLE
test performance of huge console logs with enabled timestamps plugin

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#729]
in 4.x we commented for most of our jobs: "context.timestamps {"
in 5.0 this plugin was upgraded from 1.10 to 1.11.3: https://github.com/jenkinsci/timestamper-plugin/releases

we have to enable again "context.timestamps {" and test using debug mode how console logs are displayed now

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/730

**Comment by okamara** [comment]
@ilya-varchenya could you please add details how to check this fix?

**Comment by ilya-varchenya** [comment]
Set LOG_LEVEL = DEBUG - it will give you long logs.
Verify, that scrolling doesn't stuck and works as usual

**Comment by okamara** [comment]
@ilya-varchenya do you mean Open Jenkins Config page and set Enable Debug Mode ?

**Comment by okamara** [comment]
Steps:
1. Open Jenkins Config page and set Enable Debug Mode
2. Scan Web demo test job
3. Open Console log
Actual result: Logs are not stuck
Expected result: I hope it is correct case for this ticket
@ilya-varchenya  is it expected case or not?
