### ISSUE TITLE
CarinaReport Logs/Demo links are corrupted

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#740]
Due to the invalid **-Dreport_url="{must_override}1/CarinaReport"** java arg value links to Logs/Demo inside published CarinaReport are invalid as well:
http://demo.qaprosoft.com/jenkins/job/qaprosoft/job/carina-demo/job/Web-Demo-Test/1/CarinaReport/%7Bmust_override%7D1/CarinaReport/1589402979155/56345176-2e74-46ca-9cf1-331c2fd6ec5a/test.log

open any job, activate CarinaReport, click onto the Logs
-> page can't be opened

**Comment by vdelendik** [comment]
Logs link is fixed. Demo should be fixed on carina side.
test scenario:
after clear.sh run any job. CarinaReport->Logs open text console log successfully
Demo -> open the same report

**Comment by okamara** [comment]
Fixed.
