### ISSUE TITLE
remove support of jenkinsPipelineLocales and generateMultilingualPipeline

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#741]
starting from 5.0 we don't support old 
jenkinsPipelineLocales and jenkinsPipelineBrowsers

Everything should be moved to unified "jenkinsRegressionMatrix"

**Comment by okamara** [comment]
@vdelendik could you please add details how to test this ticket

**Comment by okamara** [comment]
fixed.
