### ISSUE TITLE
maven->compile should add "jacoco:report-aggregate" only if intergation enabled

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#742]
https://github.com/qaprosoft/qps-pipeline/blob/8ac1ee62e30576ca6c829460ccea9c05d5db1cc3/src/com/qaprosoft/jenkins/pipeline/tools/maven/Maven.groovy#L88

we should verify if "JACOCO_ENABLED" and only in this case add "jacoco:report-aggregate" arg for regular maven compilation otherwise non carina repositories can't be even compiled by default:
_01:42:28  [INFO] [jenkins-event-spy] Generated /opt/jenkins/workspace/vdelendik/SeLion-test/onPush-SeLion-test@tmp/withMavenc985aead/maven-spy-20200513-224226-3153899697769547026136.log
01:42:28  [ERROR] No plugin found for prefix 'jacoco' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/root/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
01:42:28  [ERROR]_

**Comment by sandinosanchez** [comment]
Changes could be seeing in #743 
Pre conditions: JENKINS_MASTER=5.0-beta11

Test case:
  1. Run registerRepository with https://github.com/vdelendik/SeLion-test

Expected results:
  1. registerRepository and onPushJob executed successfully

**Comment by dhreben** [comment]
Verified
<img width="937" alt="Screen Shot 2020-05-15 at 13 22 27" src="https://user-images.githubusercontent.com/50950954/82044049-4c34d800-96b5-11ea-8c55-19b62b9451a6.png">
