### ISSUE TITLE
unify tokens and creds manipulation

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#746]
too many code duplicates discovered getting all kind of tokens and credentials from jenkins storage.
need to move this fucntionality into the AbstractRunner and provide fancy methods to get everything using the single code base

**Comment by vdelendik** [comment]
done: https://github.com/qaprosoft/qps-pipeline/pull/747

test scenario: test after clear regular sanity check and verify that web tests are started, results registered to zafira

**Comment by dhreben** [comment]
Verified
