### ISSUE TITLE
testrail-updater job is created with mistake

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#750]
![image](https://user-images.githubusercontent.com/4551455/82261763-4dd9f680-9968-11ea-89cb-356d8802d95d.png)

**Comment by vdelendik** [comment]
RegisterTestRailCredentials job generate corrupted pipeline code for testrail-updater job:
@Library('QPS-Pipeline')
@Library('null')
import null;
new null(this).sendTestRailResults()

but it should be always:
@Library('QPS-Pipeline')
import com.qaprosoft.jenkins.pipeline.runner.maven.QARunner;;
new com.qaprosoft.jenkins.pipeline.runner.maven.QARunner(this).sendTestRailResults()

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/235

**Comment by dhreben** [comment]
fixed
