### ISSUE TITLE
remove pipelineLibrary and runnerClass from registerOrganization

### ISSUE THREAD

**Issue by ilya-varchenya** [qaprosoft/qps-pipeline#753]
It seems that there is no sense in providing pipelineLibrary and runnerClass during registerOrganization.
so action plan:

remove those args from default job
registerRepository job which is created by jobDSL should have above textfields as extensible editable fields.
pipelineLibrary: QPS-Pipeline
runnerClass should have such values by default
com.qaprosoft.jenkins.pipeline.runner.maven.Carina
com.qaprosoft.jenkins.pipeline.runner.maven.TestNG
com.qaprosoft.jenkins.pipeline.runner.maven.JUnit
com.qaprosoft.jenkins.pipeline.runner.maven.Runner
Need to try reuse global choice list as we do for gc_BUILD_PRIORITY

**Comment by ilya-varchenya** [comment]
Related ticket https://github.com/qaprosoft/jenkins-master/issues/225

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/754

**Comment by okamara** [comment]
@ilya-varchenya could you please add steps for verification this ticket.
I see fields pipelineLibrary and runnerClass for create Repository

**Comment by ilya-varchenya** [comment]
@okamara 
1. sudo ./clear.sh
2. change jenkins-master tag to 5.1-beta1 (nano .env.original)
3. ./setup.sh <your_machine_host_name>
4. ./start.sh
5. open jenkins
6. change pipeline-branch to develop
7. open Management_Jobs/RegisterOrganization/
7.1. There must absent pipelineLibrary and runnerClass fields
8. open <your_organisation>/RegisterRepository
8.1 here must be pipelineLibrary and runnerClass parameters with next default values:
![image](https://user-images.githubusercontent.com/44428408/82790240-6bc9be80-9e74-11ea-93a8-2b0e46b4e1e8.png)
8.2 set repo parameters and run this job
8.3 run any test-job
9. (it's related to jenkins-master) also check that there're next parameters (with values) in Manage Jenkins/Configure System like on picture
![image](https://user-images.githubusercontent.com/44428408/82790891-7fc1f000-9e75-11ea-9168-fe543cfa1310.png)

**Comment by okamara** [comment]
Fixed.
