### ISSUE TITLE
Change default runner class in RegisterRepository job

### ISSUE THREAD

**Issue by ilya-varchenya** [qaprosoft/qps-pipeline#758]
Change default runner class in RegisterRepository job from QARunner to appropriate one from this list:
com.qaprosoft.jenkins.pipeline.runner.maven.TestNG
com.qaprosoft.jenkins.pipeline.runner.maven.JUnit
com.qaprosoft.jenkins.pipeline.runner.maven.Runner
com.qaprosoft.jenkins.pipeline.runner.gradle.Runner

**Comment by vdelendik** [comment]
default one supposed to be carina related, exact name - TBD

**Comment by vdelendik** [comment]
done except JUnit as it is not finished yet
com.qaprosoft.jenkins.pipeline.runner.maven.TestNG
com.qaprosoft.jenkins.pipeline.runner.maven.Runner
com.qaprosoft.jenkins.pipeline.runner.gradle.Runner

**Comment by okamara** [comment]
Verified via 5.2 version. Fixed.
