### ISSUE TITLE
Refactor QARunner build method to execute Build job

### ISSUE THREAD

**Issue by sandinosanchez** [qaprosoft/qps-pipeline#764]
As of now the build method executes a normal or cron job. Need to refactor either the build() or runJob() methods to be able to execute job created in #752

**Comment by vdelendik** [comment]
PR: https://github.com/qaprosoft/qps-pipeline/pull/837

**Comment by vdelendik** [comment]
fixed: https://github.com/qaprosoft/qps-pipeline/pull/837
@okamara - Sandino knows details howto test:)

**Comment by sandinosanchez** [comment]
@okamara added test steps, ping me if any trouble while testing 

Environment:

 - jenkins-master:5.1-beta4
 - sonarqube:2.2-beta1
 - pipeline-branch > develop
 - infra-branch: develop

Objective:

 - Verify that the Build job executes sucessfully in both carina and carina-demo repositories.

Pre conditions:
 - Latest changes from carina and carina-demo fetched into your forked repositories
 - Organization job executed
 - Carina repository registered with runnerClass > com.qaprosoft.jenkins.pipeline.runner.maven.Runner
 - Carina-demo repository registered 

Test scenario:

 1. Browse carina-demo folder > SYSTEM > Build > Build with parameters
 2. in mvn goals put: mvn clean install test -Dsuite=api
 3. Browse carina folder > SYSTEM > Build > Build with parameters > build (leave the parameters as default, just click build)

Expected results:

 2. Api suite executed, look for the following in the jenkins Build job logs:

```
2020-07-07 13:22:23 Reflections [main] [INFO] Reflections took 174 ms to scan 2 urls, producing 34 keys and 230 values 
2020-07-07 13:22:23 CarinaListener [main-1] [INFO] CARINA_CORE_VERSION: 6.4.37
2020-07-07 13:22:23 Messager [TestNG-test=User API tests-1-1] [INFO]  TEST [User API tests - testCreateUser] STARTED at [13:22:23 2020-07-07]
2020-07-07 13:22:24 AbstractApiMethodV2 [TestNG-test=User API tests-1-16] [INFO] Base properties loaded: api/users/user.properties
2020-07-07 13:22:26 AbstractApiMethod [TestNG-test=User API tests-1-16] [INFO] Request method:	POST
```
 And the result of the Build job must be successful

3. Build job executed, look for the following in the jenkins Build job logs:

```
[INFO] Reactor Build Order:
[INFO] 
[INFO] Carina Core - Multi Module                                         [pom]
[INFO] Carina Core Commons                                                [jar]
[INFO] CryptoTool Carina Core                                             [jar]
[INFO] Carina Core Utils                                                  [jar]
[INFO] BrowserMobProxy Core                                               [jar]
[INFO] Carina Core API                                                    [jar]
[INFO] Carina DataProvider                                                [jar]
[INFO] AWS S3 Helper Utility                                              [jar]
[INFO] Carina Reporting Module                                            [jar]
[INFO] Carina WebDriver Core                                              [jar]
[INFO] AppCenter Utility                                                  [jar]
[INFO] Carina Core                                                        [jar]
```

And the result of the Build job must be successful

**Comment by okamara** [comment]
I see that Carina repository doesn't contain runnerClass > com.qaprosoft.jenkins.pipeline.runner.maven.Runner

**Comment by okamara** [comment]
Tested. Fixed.

**Comment by okamara** [comment]
Reverified. Fixed.
