### ISSUE TITLE
logger for jobdsl has empty lines

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#770]
need refactor logging to avoid empty line printing for jobdsl

**Comment by vdelendik** [comment]
done: https://github.com/qaprosoft/qps-pipeline/pull/769
Test scenario: run RegisterRepository job
1) all pipeline/jobdsl jobs script shouldn't produce empty lines anymore
2) every message has prefix:
[INFO], [WARNING], [ERROR] or [DEBUG]

**Comment by okamara** [comment]
Tested on qps-pipeline- develop: I saw only INGO prefix
<img width="1031" alt="Screen Shot 2020-05-26 at 2 45 41 PM" src="https://user-images.githubusercontent.com/32964663/82897045-ac523680-9f5f-11ea-85fe-7423157a6e4e.png">
