### ISSUE TITLE
remove "test_run_rules" field from TestJobFactory

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#771]
no need default "test_run_rules" filed by default for test jobs. For those who really need it - they can use extended possibility to generate any field.
Also in scope of this ticket please submit doc enhancement for qps-infra to publish detailed info how can "test_run_rules" can be used efficiently

**Comment by ilya-varchenya** [comment]
Created new ticket: https://github.com/qaprosoft/qps-infra/issues/187

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-infra/issues/187

**Comment by okamara** [comment]
@ilya-varchenya how I can check this ticket?

**Comment by ilya-varchenya** [comment]
Check that there's no such field in test-jobs

**Comment by okamara** [comment]
I didn't find this field in configure of Job.
