### ISSUE TITLE
collect all values of "getPipelineScript()"

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#775]
let's collect to private google spreadsheet information about jobdsl factory class and their pipeline value

**Comment by ilya-varchenya** [comment]
Need more information

**Comment by ilya-varchenya** [comment]
@vdelendik task was done and a table was created
I sent a link to you in slack

**Comment by okamara** [comment]
@vdelendik or @ilya-varchenya could you add details for verification this ticket?
