### ISSUE TITLE
onlyUpdated field is not available for private pipelines

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#781]
in scope of 5.0 we made a decision based on QARunner:
https://github.com/qaprosoft/qps-pipeline/blob/54b200557012f0486c2ae218a3e732026b91435b/src/com/qaprosoft/jenkins/jobdsl/factory/pipeline/hook/PushJobFactory.groovy#L52

As result we lost this field for all qa private pipelines. Need to think better about verification step, maybe reuse existing object and it's runner class to verify if it extends QARunner

**Comment by sandinosanchez** [comment]
Changes could be seeing in #796

environment:
 - jenkins-master:5.1-beta1
 - infra-branch: master
 - qps-pipeline-branch: develop

Test scenario:
 1. run registerOrganization
 2. Ask @vdelendik for proper pipelineLibrary and runnerClass params for registerRepositoryJob
 3. navigate into the onPushJob -> build with parameters
 
Expected results:
 1. organization folder created.
 2. onPushJob executed successfully
 3. checkbox onlyUpdated present

**Comment by dhreben** [comment]
@sandinosanchez 
When we run Pipeline RegisterRepository - Pipeline library and runnerClass parameters we use default values (default values are empty) or pipelineLibrary: QPS-Pipeline, runnerClass: com.qaprosoft.jenkins.pipeline.runner.maven.QARunner ?

**Comment by sandinosanchez** [comment]
@dhreben for those values ping @vdelendik

**Comment by okamara** [comment]
Tested via jenkins: 5.1_beta3, qps-infra: develop, pipeline: develop;

<img width="723" alt="Screen Shot 2020-06-15 at 1 57 38 PM" src="https://user-images.githubusercontent.com/32964663/84668962-edb97e80-af2c-11ea-93da-d95cdabd5445.png">

**Comment by okamara** [comment]
<img width="1105" alt="Screen Shot 2020-06-15 at 5 25 25 PM" src="https://user-images.githubusercontent.com/32964663/84669183-3f620900-af2d-11ea-85fc-fc0a65658a92.png">

**Comment by dhreben** [comment]
https://github.com/qaprosoft/qps-pipeline/issues/812

**Comment by vdelendik** [comment]
it should be fixed by this PR: https://github.com/qaprosoft/qps-pipeline/pull/814

**Comment by okamara** [comment]
It was verified on private pipeline via https://github.com/qaprosoft/qps-pipeline/issues/811
