### ISSUE TITLE
need to refactor executing maven goals

### ISSUE THREAD

**Issue by ilya-varchenya** [qaprosoft/qps-pipeline#784]
Need to refactor executing maven goals
We use compile() method only in Sonar class. Let's move it's logic into Sonar.scan()

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/785

**Comment by ilya-varchenya** [comment]
For QA:
Check the logs from the onPushJob. Sonar scan shouldn't fail onPushJob

**Comment by okamara** [comment]
Tested on qps pipeline - develop. Fixed.
