### ISSUE TITLE
Make possible to call maven from anywere

### ISSUE THREAD

**Issue by ilya-varchenya** [qaprosoft/qps-pipeline#787]
Check Jenkins feature Shared Libraries. It allows to create it by vars directory
Also refactor code: Mixin library must be excluded

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/786

**Comment by vdelendik** [comment]
refactored mavenBuild using global vars (removed Mixin usage).
test scenario: 
1) using develop branch register organization/repo.
2) verify pull request checkers
3) run api_regression and web_regression cron jobs for carina-demo

**Comment by okamara** [comment]
Tested on qps-infra develop, jenkins-master:5.1-beta1, pipeline - develop
