### ISSUE TITLE
unified build naming process needed

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#789]
1. declare in AbstractRunner default buildNameTemplate variable and getter/setter
protected String buildNameTemplate = "${BUILD_NUMBER}"

2. declare buildNameSeparator
protected final String BUILD_NAME_SEPARATOR = "|"

3. think about valid buildName template for each runner
AbstractRunner, Runner -> "${BUILD_NUMBER}${branch}"
QARunner -> "${BUILD_NUMBER}${suite}${branch}${env}${browser}${browserVersion}${locale}${language}"
Maybe add "node" label as well for all runners...

4. create new method in AbstractRunner to set build name. Execute new method in the AbstractRunner constructor (need to test if it is valid assumption)

5. new method should try to resolve each ${var} variable and if it is not empty/null replace by actual value with separator, i.e.
"${BUILD_NUMBER}${suite}${branch}${env}${browser}${browserVersion}${locale}${language}"
->
"100|demo-suite|master|PROD|chrome"
for above example such variables missed: ${browserVersion}${locale}${language}
Note: move/remove all build naming related functionality from QARunner->prepareBuild method

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/810

**Comment by ilya-varchenya** [comment]
Test scenario:
1. Register repository
2. Run full regression
3. Check that names of builds become like that
![image](https://user-images.githubusercontent.com/44428408/85004506-4e7ccd00-b160-11ea-920c-55cdecd3421d.png)

3.1 Naming of builds must follow this pattern "${BUILD_NUMBER}${suite}${branch}${env}${browser}${browserVersion}${locale}${language}"
3.2 Check that there's no "NULL" or "null" in build name
3.3 Check that separators "|" are not repeated
3.4 Check that build name isn't end with separator character

**Comment by okamara** [comment]
Tested. Fixed.

**Comment by vdelendik** [comment]
#292|...|master|QA|${locale}|${language}
in 5.2 pipeline I still see that locale and language can't be displayed
![image](https://user-images.githubusercontent.com/4551455/91753342-69dc6d80-ebd0-11ea-8401-649872c35a09.png)

**Comment by ilya-varchenya** [comment]
![image](https://user-images.githubusercontent.com/44428408/91843556-9dfe6f80-ec5e-11ea-8ca0-5b1ea16f5240.png)

**Comment by ilya-varchenya** [comment]
Test scenario:
1. Register repository
2. Add into some job two string parameters:
![image](https://user-images.githubusercontent.com/44428408/91844813-c8e9c300-ec60-11ea-9ca3-933cd61f8211.png)
3. Check that names of builds become like that
![image](https://user-images.githubusercontent.com/44428408/85004506-4e7ccd00-b160-11ea-920c-55cdecd3421d.png)
3.1 Naming of builds must follow this pattern "#${BUILD_NUMBER}${suite}${branch}${env}${browser}${browserVersion}${locale}${language}"
3.2 Check that there's no "NULL" or "null" in build name
3.3 Check that separators "|" are not repeated
3.4 Check that build name isn't end with separator character

**Comment by dhreben** [comment]
Fixed:

<img width="911" alt="Screen Shot 2020-09-02 at 11 18 08" src="https://user-images.githubusercontent.com/50950954/91956894-fd678880-ed0d-11ea-8fac-5dbf7526aac1.png">
