### ISSUE TITLE
add browser_version support for dsl/pipeline and cron

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#79]
for now browser_version was removed completely from job arguments.
I suggest:
1) return it back as separate field (maybe hidden for the beginning
2) adjust jobdsl for web use-case to insert appropriate hiddent fields
3) improve cron parser supporting new notation with browser_version, i.e.:
old one:
    <parameter name="jenkinsPipelineBrowsers" value="chrome,firefox,ie"/>
new one
    <parameter name="jenkinsPipelineBrowsers" value="chrome,firefox,ie 9.0,ie,edge 16.0"/>

-> So if browsername contain space in jenkinsPipelibebrowsers then it is supposed to be a version. So we have to parse it correctly and generate 5 jobs during startup for:
-chrome *
- firefox *
- ie 9.0
-ie *
-edge 16.0

**Comment by tsvrko** [comment]
added https://github.com/qaprosoft/qps-pipeline/pull/80
