### ISSUE TITLE
5.0: sonar can't use ssh connection

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#790]
sonar has their own and hardcoded https scmClient.
Need unified solution to have single git client for every pipeine operation where you can change easily ssh or https protocol to use.

**Comment by vdelendik** [comment]
resolved: https://github.com/qaprosoft/qps-pipeline/pull/792
we already verified that using customized ssh client works fine. So this one might be verified in scope of regular regression testing registering org, cloning repos and running sample tests.
changes backported to develop branch as well: https://github.com/qaprosoft/qps-pipeline/pull/793

**Comment by okamara** [comment]
Tested via pipeline branch 5.0.5, jenkins-master 5.0.4
