### ISSUE TITLE
*.mp4 files still published as part of carina report artifacts

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#797]
we have to prohibited to publish *.mp4 into any build output report on jenkins.
the best way - explicitly allow to publish only certain number of files:
`*.html, *.js, *.css, *.jpj, *.jpeg,*.log, *.png`

**Comment by vdelendik** [comment]
done, also merged to develop: https://github.com/qaprosoft/qps-pipeline/pull/798
*.mp4 artifacts not published anymore.

in scope of testing we should verify that CarinaReport, ZafiraReport and TestNG reports can be opened successfully. Their content is not corrupted of missed icons/images etc.
Also all links inside above reports should work. I expect to see 2 new issues from QA after verification of this ticket :)

**Comment by okamara** [comment]
Created separate issue for Zafira report https://github.com/qaprosoft/qps-infra/issues/206

**Comment by okamara** [comment]
Tested: jenkins-master: 5.1-beta1,qps-infra- develop, pipeline- develop
Zafira: ui: 1.3.0; server: 1.3.1.
