### ISSUE TITLE
global groovy code formatting

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#799]
as we have more or less consolidated formatter which uses spaces for tab we can do one global code formatting in develop branch

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/808

**Comment by ilya-varchenya** [comment]
Test with tradition scenario
Just make sure that everything works well

**Comment by okamara** [comment]
Env. : jenkins:5.1_beta3;qps-infra - develop; pipeline- develop
I see that "Build" job scanning with error:
<img width="1108" alt="Screen Shot 2020-06-15 at 5 12 27 PM" src="https://user-images.githubusercontent.com/32964663/84667864-91099400-af2b-11ea-832e-5e4432c43d2c.png">

**Comment by vdelendik** [comment]
@okamara that's not due to this ticket. let's close as is and submit new one.
thanks!

**Comment by okamara** [comment]
Created a separate bug https://github.com/qaprosoft/qps-infra/issues/211
