### ISSUE TITLE
class renaming for maven runners needed

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#800]
1. let's rename com.qaprosoft.jenkins.pipeline.runner.maven.QARunner to
com.qaprosoft.jenkins.pipeline.runner.maven.TestNG

2. new empty com.qaprosoft.jenkins.pipeline.runner.maven.QARunner should be generated to support old repositories
class QARunner extends TestNG
Note: empty means nothing to override or declare except constructor and imports

3. in scope of renaming please review changes in this PR: https://github.com/qaprosoft/qps-pipeline/pull/796/files#diff-ad43c83289f46d8a1a2507cf3f8e0e93R173

"in QARunner" must be replaced by "in "TestNG"

**Comment by sandinosanchez** [comment]
Changes could be seing in #801 

environment:
 - jenkins-master:5.1-beta1
 - infra-branch: develop
 - qps-pipeline-branch: develop

Test scenario:
 1. run registerOrganization
 2. run registerRepository

Expected results:
 1. Organization folder created
 2. in registerRepository->build with params-> runnerClass and pipelineLibrary should be:
 - com.qaprosoft.jenkins.pipeline.maven.runner.TestNG by default.
 - QPS-Pipeline
 2.1 onPush job executed successfully

**Comment by okamara** [comment]
Fixed.Verified via environment:

jenkins-master:5.1-beta3
infra-branch: develop
qps-pipeline-branch: develop

**Comment by okamara** [comment]
<img width="723" alt="Screen Shot 2020-06-15 at 1 57 38 PM" src="https://user-images.githubusercontent.com/32964663/84650542-20ee1480-af11-11ea-8283-2bdf7157f2d5.png">
