### ISSUE TITLE
improve ListViewFactory registration to avoid mass warnings in logs

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#802]
During TestNG project scanning each job belongs to several views by project, owner, platform.
As result we registerObject several times for the same categories and got a lot of warnings in logs like:

WARNING! key WEB_VIEW already defined and will be replaced!
WARNING! key IOS_VIEW already defined and will be replaced!
WARNING! key ANDROID_VIEW already defined and will be replaced!
...

let's improve our [registerObject](https://github.com/qaprosoft/qps-pipeline/blob/3d063db465bd1d75acda941a22f3d5dcac51821e/src/com/qaprosoft/jenkins/pipeline/runner/maven/QARunner.groovy#L282) method to avoid all kind of warnings when ListViewFactory is duplicated. Or even do not register one more object for this class if it is already registered.

Major note: we should think about possibility of custom "ListViewFactory" jobdsl implementations, in this case logic with skipping registration might be wrong.

Also need to think about extra warnings messages and howto avoid them for onPush

**Comment by sandinosanchez** [comment]
changes could be seeing in #815 

env:
 - jenkins-master:5.1-beta1
 - infra-branch= develop
 - QPS_PIPELINE_BRANCH= develop
 - QPS_LOG_LEVEL= INFO

Test scenario:
 1. run registerOrganization
 2. run registerRepository with carina-demo

Expected results:
 1. organization folder created
 2. onPushJob executed successfully, no more warning regarding duplicated objects appears. 
<img width="880" alt="Screen Shot 2020-06-17 at 01 49 50" src="https://user-images.githubusercontent.com/43247306/84856438-14ff7100-b03d-11ea-9707-fd96d1144f88.png">

**Comment by okamara** [comment]
Verified on  jenkins:5.1_beta3;qps-infra - develop; pipeline- develop. Still repro the issue. Will check on jenkins:5.1_beta1

**Comment by okamara** [comment]
Fixed.
