### ISSUE TITLE
rename zafira -> reporting

### ISSUE THREAD

**Issue by ilya-varchenya** [qaprosoft/qps-pipeline#806]

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/804

**Comment by ilya-varchenya** [comment]
Test scenario:
Run tradition flow, check that zafira integration works

**Comment by dhreben** [comment]
Verified
<img width="1384" alt="Screen Shot 2020-06-12 at 16 25 22" src="https://user-images.githubusercontent.com/50950954/84507331-51dc0880-acc9-11ea-9a9b-e61111656695.png">
