### ISSUE TITLE
Register repository contains empty value for runner field

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-pipeline#807]
Tested on jenkins master: 5.0.4, pipleline branch - develop.
Issue not repro on pipleline branch - 5.0.0.
<img width="795" alt="Screen Shot 2020-06-11 at 3 06 06 PM" src="https://user-images.githubusercontent.com/32964663/84384693-03f6d000-abf7-11ea-8b8f-479c82fd4dca.png">

It is a blocker.

**Comment by ilya-varchenya** [comment]
Issue isn't reproduced on 
qps-pipeline branch: develop
jenkins-master: 5.1-beta1

**Comment by vdelendik** [comment]
it is fixed now in qps-infra: develop branch.
test scenario:
do ./clear.sh
get latest changes for qps-infra in develop branch
./setup.sh

after that all components should be tested using QPS_PIPELINE_BRANCH=develop as well

**Comment by okamara** [comment]
Tested. Fixed.
