### ISSUE TITLE
Create custom private pipeline as carina-demo

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-pipeline#811]

**Comment by vdelendik** [comment]
need sample private pipeline in open source to demo how we can organize all kind of private logic and override any action in default qps-pipeline

**Comment by sandinosanchez** [comment]
private pipeline delivered in https://github.com/qaprosoft/carina-demo-pipeline

 env:
   - jenkins-master:5.1-beta3
   - infra branch > devleop
   - pipeline branch > develop

Test scenario:
 1. Go to jenkins global configuration
 2. In Global Properties add the following: 
<img width="1000" alt="Screen Shot 2020-06-26 at 15 50 08" src="https://user-images.githubusercontent.com/43247306/85890965-b8cae880-b7c4-11ea-9377-0dbbf5061c43.png">

 3. In Global Pipeline Libraries add the following:
<img width="1010" alt="Screen Shot 2020-06-26 at 15 48 34" src="https://user-images.githubusercontent.com/43247306/85890912-a6e94580-b7c4-11ea-87a6-4820e7c39026.png">

 4. Run registerOrganization
 5. Run registerRepository with:
    a. pipelineLibrary > QPS-pipeline-demo
    b. runnerClass > com.qaprosoft.jenkins.pipeline.runner.maven.CarinaDemo
 6. Browse WebDemoTest > Build with parameters

Expected results: 

  5. onPushJob executed successful
  6. boolean param "debug" should be visible

**Comment by okamara** [comment]
Re-verified. Fixed.
