### ISSUE TITLE
The RegisterRepository doesn't work for private libraries

### ISSUE THREAD

**Issue by dhreben** [qaprosoft/qps-pipeline#812]
environment:

jenkins-master:5.1-beta3
infra-branch: develop
qps-pipeline-branch: develop

<img width="1005" alt="Screen Shot 2020-06-15 at 20 42 33" src="https://user-images.githubusercontent.com/50950954/84688885-bfe23300-af48-11ea-8752-9b8315a2d86c.png">

**Comment by vdelendik** [comment]
added private library loading before making validation of inheritance: https://github.com/qaprosoft/qps-pipeline/pull/814

fix should be accesible in develop qps-infra: branch branch

**Comment by okamara** [comment]
It was verified on private pipeline here https://github.com/qaprosoft/qps-pipeline/issues/811
