### ISSUE TITLE
Can't clone a repository with a custom private pipeline.

### ISSUE THREAD

**Issue by dhreben** [qaprosoft/qps-pipeline#813]
environment:

jenkins-master:5.1-beta3
infra-branch: develop
qps-pipeline-branch: develop

<img width="799" alt="Screen Shot 2020-06-15 at 20 15 43" src="https://user-images.githubusercontent.com/50950954/84686757-35e49b00-af45-11ea-9af2-c0773d1883bf.png">

**Comment by vdelendik** [comment]
it was a configuration issue. we registered private pipeline incorrectly.
there is a requirement to use global env vars like we do for QPS
CUSTOM_PIPELINE_GIT_URL and CUSTOM_PIPELINE_GIT_BRANCH.

tested successfully on stage

**Comment by okamara** [comment]
Tested during verification custom private pipeline via https://github.com/qaprosoft/qps-pipeline/issues/811
