### ISSUE TITLE
Investigate how is secure to delete devicePool parameter

### ISSUE THREAD

**Issue by ilya-varchenya** [qaprosoft/qps-pipeline#817]
Investigate how is secure to delete devicePool parameter 
https://github.com/qaprosoft/qps-pipeline/blob/18fd0192872ccb7d1a73c2ffe836abb186a2971e/src/com/qaprosoft/jenkins/pipeline/runner/maven/TestNG.groovy#L723

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/824

**Comment by ilya-varchenya** [comment]
Ticket is waiting for approval from @vdelendik

**Comment by okamara** [comment]
@ilya-varchenya could you please add details for verification this ticket?

**Comment by ilya-varchenya** [comment]
@okamara, just verify by traditional test scenario
There were remains of old logic. That code was moved to https://github.com/qaprosoft/carina

**Comment by okamara** [comment]
Fixed.
