### ISSUE TITLE
unchecked enableVideo doesn't disable video recording

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#818]
it was discovered using develop branch that unchecking enableVideo don't produce valid capabilities, i.e.:
[Pipeline] echo
enableVideo=false
...

among maven goals it is mistakenly specified using:
-DenableVideo="false"

as result we still try to enable recording video 
capabilities.enableVideo=true

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/819

**Comment by ilya-varchenya** [comment]
Test scenario:
1. Run any job with unchecked enableVideo parameter
![image](https://user-images.githubusercontent.com/44428408/85290825-4dbaa280-b4a2-11ea-98f7-9104864f2f62.png)
2. Find in logs that capabilities.enableVideo maven goal equals to false
![image](https://user-images.githubusercontent.com/44428408/85290977-8eb2b700-b4a2-11ea-9923-e04ec793f982.png)

**Comment by okamara** [comment]
Tested on jenkins-master:5.1-beta3,qps-infra - develop , pipeline - develop. 
In the case when I uncheck enableVideo parameter. Open Test run results via zafira - Video is disabled.
<img width="1385" alt="Screen Shot 2020-06-25 at 10 14 05 PM" src="https://user-images.githubusercontent.com/32964663/85785465-ff233780-b731-11ea-9c9d-cce25c0e561c.png">
 @ilya-varchenya  is it expected result for this case?

**Comment by ilya-varchenya** [comment]
Yep, we want it like that)

**Comment by okamara** [comment]
Done.
