### ISSUE TITLE
investigate if we can remove TESTRAIL_ENABLE and QTEST_ENABLE from Configuration

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#820]
if I remember correctly in 5.0 testrail and qtest logic was reorganized. If we register appropriate credentials then integration is enabled.
So looks like globally there is no need to have in Configuration.groovy:
```
TESTRAIL_ENABLE("testrail_enabled", "false"),
QTEST_ENABLE("qtest_enabled", "false"),
```

at the same time we can't remove refernce to "testrail-enabled" and "qtest_enabled" arguments as this params are managed by engineers on jobs and crons level

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/823

**Comment by ilya-varchenya** [comment]
Ticket is waiting for @vdelendik approval

**Comment by vdelendik** [comment]
#823 merged

**Comment by okamara** [comment]
Tested on jenkins-master:5.1-beta3 , qps-infra - develop, pipeline- develop.
Open a job configuration page and verify that there is no testrail_enable, and qtest_enable.
@ilya-varchenya is it correct verification case for this ticket?

**Comment by ilya-varchenya** [comment]
@okamara 
Test scenario:
1. Run Management_Jobs/RegisterTestRailCredentials and Management_Jobs/RegisterQTestCredentials for your organisation folder with 
![image](https://user-images.githubusercontent.com/44428408/85823574-6cf94e80-b786-11ea-8c03-2ba6b88411f5.png)
![image](https://user-images.githubusercontent.com/44428408/85823645-987c3900-b786-11ea-9399-f6cd0828401a.png)
2. Then run RegisterRepository for carina-demo
![image](https://user-images.githubusercontent.com/44428408/85823893-25bf8d80-b787-11ea-89df-0713aba9f1ea.png)
3. After that go into Configure of any test job (for example api-job)
![image](https://user-images.githubusercontent.com/44428408/85824011-71723700-b787-11ea-83cf-ccf7de9978d7.png)
4. Add boolean parameters **testrail_enabled** and **qtest_enabled** 
![image](https://user-images.githubusercontent.com/44428408/85824056-91a1f600-b787-11ea-83cd-2fdb63001dac.png)
![image](https://user-images.githubusercontent.com/44428408/85824104-ad0d0100-b787-11ea-8c0c-059a02f7da70.png)
5. Now need to run this test-job with that ticked parameters
![image](https://user-images.githubusercontent.com/44428408/85824183-d7f75500-b787-11ea-9d1e-6157b671d48a.png)
6. Check console output (logs) for this strings
![image](https://user-images.githubusercontent.com/44428408/85824258-0bd27a80-b788-11ea-8aa9-48af2f37e015.png)

**Comment by okamara** [comment]
Test is passed. Fixed.
<img width="929" alt="Screen Shot 2020-06-26 at 1 16 15 PM" src="https://user-images.githubusercontent.com/32964663/85846923-47346f80-b7af-11ea-9860-c3dbbe7beb98.png">
