### ISSUE TITLE
testrail integration is too slow

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#825]
sometines pushing results to testrail even slower then tests execution

**Comment by vdelendik** [comment]
done: https://github.com/qaprosoft/qps-pipeline/pull/826

**Comment by vdelendik** [comment]
need to think about verification strategy as it is already applied as a patch on production...

**Comment by okamara** [comment]
@vdelendik could you please add details or steps how I can test this ticket?

**Comment by okamara** [comment]
Tested via Regression run on jenkins:5.0.3,qps-infra:develop, pipeline:develop.
