### ISSUE TITLE
Launchers are not created during Scanning repository

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-pipeline#831]
During scanning repo in Zebranner Launchers are not created

**Comment by vdelendik** [comment]
can't reproduce... let's test as only release candidate qps-infra build appear

**Comment by okamara** [comment]
Will retest on release candidate qps-infra build

**Comment by vdelendik** [comment]
extra fixes merged to develop: https://github.com/qaprosoft/qps-pipeline/pull/850
