### ISSUE TITLE
Update sonar functionallity to handle 7.9.3 version

### ISSUE THREAD

**Issue by sandinosanchez** [qaprosoft/qps-pipeline#833]
In 5.1 we are going to update sonarqube to 7.9.3 so all previous logic needs to be updated aswell. New functionallity to handle pr decorator and decompose old sonar class into the SonarCient to suport custom sonarqube instances.

**Comment by sandinosanchez** [comment]
Environment: 
 - jenkins-master:5.1-beta4
 - infra-branch > develop
 - pipeline-branch > develop

Objective:
 - Test the new version of sonarqube and verify that all the features(onPush sonar analysis, pr decorator) work as intended with embeded and custom sonarqube.

Pre conditions:
 - GithubApp created and configured(ping me for the configuration)
 - Ghprbhook configured in jenkins
 - Webhooks configured for carina-demo

Test scenario:
 1. Run registerOrganization job
 2. Run registerRepository job with carina-demo 
 3. Create a branch from master in your froked carina-demo
 4. Modify a class with some unused fields(ping me for information about this one)
 5. Create a pr from that branch to master

Expected results

 2. onPush job executed successfully
 5. sonar scanner results should be displayed in the pr > checks tabs
![Screenshot from 2020-07-06 10-16-19](https://user-images.githubusercontent.com/43247306/86597182-caa14e00-bf71-11ea-93cb-6d3108dfa9c3.png)

**Comment by okamara** [comment]
Verified on my env. Done. 
<img width="932" alt="Screen Shot 2020-07-06 at 10 29 51 PM" src="https://user-images.githubusercontent.com/32964663/86632712-6a91c280-bfd8-11ea-980a-1ca2db4adcbb.png">

**Comment by sandinosanchez** [comment]
some improvements where made in #836 need to re test with previous test steps, same environment.

@okamara ping me if you need help with the configuration.

**Comment by okamara** [comment]
Reverified. Fixed.
