### ISSUE TITLE
launcher job can't determine jobType and run everything on master

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#834]
1) we have to run all undefined jobs on "default" slave instead of master. 
2) need a ticket to assign "default" slave label for our single slave

**Comment by vdelendik** [comment]
fixed in 5.0.8 and ported to develop as well: https://github.com/qaprosoft/qps-pipeline/commit/4f1c87856c9e93856cd9cdd0a397677e0a863288

so as a test scenario:
1) requirements: latest qps-infra from develop with a fix for https://github.com/qaprosoft/qps-infra/issues/218
1) register new repository via test laucher
2) run "manually" registered "Carina  - API" and "Carina - Web" jobs
-> verify that real execution is assign to the slave and not api.
in job logs such message should appear:
_Suite Type: Default
[Pipeline] echo
nodeLabel: null
[Pipeline] echo
node: default_

**Comment by okamara** [comment]
Tested: Actual result ->
Suite Type: Web
[Pipeline] echo
nodeLabel: null
[Pipeline] echo
node: web

Suite Type: Api
[Pipeline] echo
nodeLabel: null
[Pipeline] echo
node: api
cc @vdelendik  is it expected?

**Comment by okamara** [comment]
Tested. Fixed.
