### ISSUE TITLE
Launcher job:Pipeline script contains incorrect value in the end 

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-pipeline#839]
@Library('QPS-Pipeline')
import com.qaprosoft.jenkins.pipeline.runner.maven.TestNG;
new com.qaprosoft.jenkins.pipeline.runner.maven.TestNG(this).build()

Actual result: build() is in the end of the script
Expected: .runJob() should be in the end of the script

**Comment by vdelendik** [comment]
fixed and available in qps-pipeline: develop branch
commit: https://github.com/qaprosoft/qps-pipeline/commit/ec44b3d2b0391b3661e379a2016897706226621e

@okamara as I remember we already tested it successfully on your env yesterday

**Comment by okamara** [comment]
Tested. Fixed.
