### ISSUE TITLE
Need to fix the creation of the Build Job for custom pipelines

### ISSUE THREAD

**Issue by sandinosanchez** [qaprosoft/qps-pipeline#840]
As of now we check for the package structure in order to add the "Build" job into the registered repository.
https://github.com/qaprosoft/qps-pipeline/blob/ec44b3d2b0391b3661e379a2016897706226621e/src/com/qaprosoft/jenkins/pipeline/Repository.groovy#L184

As a result, no "Build" job is registered for custom pipelines that doesn't have the same organization(qaprosoft).

**Comment by sandinosanchez** [comment]
@okamara  fixed in #841 

Environment:

 - jenkins-master:5.1-beta4
 - infra-branch > develop
 - pipeline-branch > develop
 - sonarqube:2.2-beta1

Objective:

 - Verify that the "Build" job is created and executed successfully for custom/private pipelines under SYSTEM view in repository folder.

Test scenario:

 1. Go to jenkins global configuration
 2. In Global Properties add the following two properties:

    - Name > CARINA_DEMO_PIPELINE_GIT_URL
    - Value > https://github.com/sandinosanchez/qps-pipeline-demo
    - Name > CARINA_DEMO_PIPELINE_GIT_BRANCH
    - Value > custom-pipeline
    
    - It should look like this once added:
<img width="658" alt="Screen Shot 2020-07-07 at 23 39 24" src="https://user-images.githubusercontent.com/43247306/86868465-1acffb80-c0ab-11ea-9728-73a67e56dfac.png">

 3. In Global Pipeline Libraries add the following library(it should look exactly like the screenshot below):

<img width="1010" alt="85890912-a6e94580-b7c4-11ea-87a6-4820e7c39026" src="https://user-images.githubusercontent.com/43247306/86868726-a5b0f600-c0ab-11ea-9831-2df422e50eb8.png">

 4. Save configuration
 5. Run registerOrganization job
 6. Run registerRepository with the followings params:
  
     - pipelineLibrary > QPS-Pipeline-demo
     - runnerClass > com.demosoft.jenkins.pipeline.runner.maven.CarinaDemo 
     - repo > carina-demo
     - it should look exactly like the screenshot below but with your scmOrg
<img width="570" alt="Screen Shot 2020-07-07 at 23 57 12" src="https://user-images.githubusercontent.com/43247306/86869798-9468e900-c0ad-11ea-97c8-655a43bff122.png">

 7. Go to the carina-demo folder > SYSTEM > Build > Build with parameters
 8. In mvn goals put: -U clean install test -Dsuite=api
 9. Click build.

Expected Results:

6. "Build" job visible under SYSTEM tab in carina-demo folder
9. Api suite executed successfully, look for the following in the jenkins Build job logs:

```
2020-07-07 13:22:23 Messager [TestNG-test=User API tests-1-1] [INFO]  TEST [User API tests - testCreateUser] STARTED at [13:22:23 2020-07-07]	
```

**Comment by okamara** [comment]
Tested on jenkins-master:5.1-beta5
infra-branch > develop
pipeline-branch > develop
sonarqube:2.2-beta1

I see errors during Register repository.

**Comment by sandinosanchez** [comment]
fixed delivered in #844 

@okamara please re test with same steps.

**Comment by okamara** [comment]
I got errors during register repository
Environment:

jenkins-master:5.1-beta5-jdk11
infra-branch > develop
pipeline-branch > develop
sonarqube:2.2-beta1
jenkins-slave:latest-alpine-jdk11
java version 11

**Comment by sandinosanchez** [comment]
@okamara after verification of #848 you should be able to test with the same steps.

**Comment by okamara** [comment]
Tested. Fixed.
Test env.

jenkins-master:5.1-beta6
infra-branch > develop
pipeline-branch > develop
sonarqube:2.2-beta1
jenkins-slave:latest-alpine
