### ISSUE TITLE
Need to delete duplicate github clone in onPushJob 

### ISSUE THREAD

**Issue by sandinosanchez** [qaprosoft/qps-pipeline#842]
There is a unnecessary duplicate github clone when executing onPushJob.

<img width="777" alt="Screen Shot 2020-07-08 at 00 32 02" src="https://user-images.githubusercontent.com/43247306/86872403-a731ec80-c0b2-11ea-8e2e-2abeddc9b4ce.png">

**Comment by sandinosanchez** [comment]
@okamara  fixed in #843 (wait for the merge into develop to start testing)

Environment: 

 - jenkins-master:5.1-beta4
 - sonarqube:2.2-beta1
 - pipeline-branch > develop
 - infra-branch: develop

Objective: 

 - Verify that the duplication of the github clone is no longer present when executing the onPushJob.

Test scenario:

 1. run registerOrganization
 2. run registerRepository with the following params:

    - pipelineLibrary > QPS-Pipeline
    - runnerClass > com.qaprosoft.jenkins.pipeline.runner.maven.TestNG
    - repo > carina-demo

Expected results:

 2. onPushJob executed successfully. Go to carina-demo folder > onPushJob > the stage view should be exactly like the screenshot below:

 
<img width="777" alt="Screen Shot 2020-07-08 at 00 40 54" src="https://user-images.githubusercontent.com/43247306/86873445-a8fcaf80-c0b4-11ea-9cfd-c752b8649712.png">

**Comment by dhreben** [comment]
fixed 
<img width="581" alt="Screen Shot 2020-07-08 at 13 51 16" src="https://user-images.githubusercontent.com/50950954/86910372-480bc080-c122-11ea-9bd0-b69b9b91a619.png">
