### ISSUE TITLE
Need to check the registration of zafiraFields for onPushJob

### ISSUE THREAD

**Issue by sandinosanchez** [qaprosoft/qps-pipeline#853]
As of now there are errors when running registerRepository, logs from onPushJob triggered by registerRepository:

```
[Pipeline] httpRequest
17:11:09  HttpMethod: POST
17:11:09  URL: http://reporting-service:8080/reporting-service/api/launchers/create
17:11:09  Content-Type: application/json
17:11:09  Authorization: *****
17:11:09  Sending request to url: http://reporting-service:8080/reporting-service/api/launchers/create
17:11:09  Response Code: HTTP/1.1 404 
[Pipeline] echo
17:11:09  [ERROR] Scan failed.
17:11:09  Something went wrong during launchers creation
[Pipeline] echo
17:11:09  [DEBUG] zafira connected
[Pipeline] echo
17:11:09  [INFO] REQUEST: {
17:11:09      "success": false,
17:11:09      "repo": "carina-demo",
17:11:09      "userId": 2,
17:11:09      "jenkinsJobs": [
17:11:09          
17:11:09      ]
17:11:09  }
[Pipeline] httpRequest
17:11:09  HttpMethod: POST
17:11:09  URL: http://reporting-service:8080/reporting-service/api/launchers/create
17:11:09  Content-Type: application/json
17:11:09  Authorization: *****
17:11:09  Sending request to url: http://reporting-service:8080/reporting-service/api/launchers/create
17:11:09  Response Code: HTTP/1.1 200 
17:11:09  Success code from [200‥200]
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // node
[Pipeline] node
Running on jenkins-slave in /opt/jenkins/workspace/qaprosoft/carina-demo/onPush-carina-demo
[Pipeline] {
[Pipeline] timestamps
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Wipe out Workspace)
[Pipeline] deleteDir
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: FAILURE
```

How to replicate:

 - infra-branch > develop
 - pipeline-branch > allow-404-zc
 - jenkins-master:5.1-rc2
 - sonarqube:2.2-beta1

Steps:

 1. run registerOrganization with qaprosoft
 2. run registerRepository with carina-demo

When the onPushJob is triggered by the registerRepository at the end of the logs before the maven compile phase we have two calls to the reporting-service-url/api/launchers/create, one with response code 404 and the other one with 200, as a result the onPushJob fails.
We need to investigate why is there a 404 response while calling the zafira endpoint.
Also we should check for the registration of zafiraHiddenParameters fields to be sure that they are being registered correctly.

**Comment by vdelendik** [comment]
fixed indirectly. scan and launchers creation is fine using zebrunner 1.0 (5.2-qps) infra
git clone --recurse-submodule --branch "develop" https://github.com/zebrunner/zebrunner.git

**Comment by okamara** [comment]
Verified. Fixed.
