### ISSUE TITLE
onPush-job fails with disabled sonarqube 

### ISSUE THREAD

**Issue by ilya-varchenya** [qaprosoft/qps-pipeline#854]
Need to create check of sonarqube status
Job must have success if there's no sonarqube url in global variables or container isn't started
![image](https://user-images.githubusercontent.com/44428408/87426059-5f95ee00-c5e7-11ea-8eb4-57f8524c3823.png)

**Comment by sandinosanchez** [comment]
fix delivered in #855 

Environment:
 - infra-branch: develop

Objective: 

 - Verify that the onPush job executes successfuly with:
    a. Jenkins > Configuration > Global Variables > SONAR_URL= (leave empty value)
    b. Jenkins > Configuration > Global Variables > Delete the SONAR_URL Global Variable
    c. The sonarqube container stopped

Pre-conditions:

 - Organization registered with qaprosoft 

Test scenario 1:

 1. Go to Jenkins > Configuration > Global Variables > remove the SONAR_URL global variable value(leave emtpy value)
 2. Run registerRepository with default values

Test scenario 2:

 1. Go to Jenkins > Configuration > Global Variables > Delete the value from SONAR_URL global variable
 2. Run registerRepository with default values(remove the carina-demo folder before doing this step)

Test scenario 3:

 1. cd qps-infra
 2. docker-compose -f sonarqube/docker-compose.yml stop (no need to stop the infra)
 3. Go to jenkins > Configuration > Global Variables > Add back the SONAR_URL variable with value=http://${INFRA_HOST}/sonarqube
 3. Run registerRepository with default values(remove the carina-demo folder before doing this step)

Expected Results:

 1. For test scenario 1:
     a. onPush job executed successfully
     b. in onPush job logs the following should be present:
     `[WARN] The url for the sonarqube server is not configured, sonarqube scan will be skipped!`


 2. For test scenario 2:
     a. onPush job executed successfully
     b. in onPush job logs the following should be present:
     `[WARN] The url for the sonarqube server is not configured, sonarqube scan will be skipped!`

3. For test scenario 3:
     a. onPush job executed successfully
     b. in onPush job logs the following should be present:
     `[WARN] The sonarqube http://your.infra.url/sonarqube server is not available, sonarqube scan will be skipped!`

Run the test scenarios in order(1,2,3)

**Comment by okamara** [comment]
Test1: - passed.
