### ISSUE TITLE
RegisterUserCredentials method should be moved to Organization class

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#861]
```
@Library('QPS-Pipeline')
import com.qaprosoft.jenkins.pipeline.Repository
new Repository(this).registerCredentials()
```

but user credentials are org related so let's move logic into the Organization

**Comment by sandinosanchez** [comment]
delivered in #913 and [#294](https://github.com/zebrunner/jenkins-master/pull/294)

**Environment**

Zebrunner CE branch > develop
pipelines branch > develop

**Pre conditions**

Make sure to run **git pull --recurse-submodules** before staring Zebrunner CE

**Objective**

Verify that the RegisterUserCredentials job works as expected.

**Test steps**

 1.  Run RegisterUserCredentials inside ManagementJobs folder with your scm account and password

**Expected results**

 1. Credentials created for the current jenkins user and scm user provided. Browse Credentials menu and look for:
<img width="1306" alt="Screen Shot 2020-10-06 at 13 37 09" src="https://user-images.githubusercontent.com/43247306/95234767-e23fdb00-07db-11eb-9752-dc3d10c95058.png">

**NOTE:** the name of your credential should be: **your-scm-user/\*\*\*\*\*(jenkins-user(usually admin) SCM token)**

**Comment by dhreben** [comment]
Verified.
<img width="1108" alt="Screen Shot 2020-10-12 at 14 39 40" src="https://user-images.githubusercontent.com/50950954/95742489-c4b9b800-0c98-11eb-9fb6-75ee7dc408ed.png">

**Comment by vdelendik** [comment]
reopened and assigned for th next release as PR wasn't merged and have a conflicts
