### ISSUE TITLE
provide stable solution for iam auth refresh end-point

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#863]
https://github.com/qaprosoft/qps-pipeline/blob/a7b85726bdcd03b10025378ea2b7f9fc9e8c5833/src/com/qaprosoft/jenkins/pipeline/integration/zafira/ZafiraClient.groovy#L275

serviceURL.split("reporting-service")[0] + "api/iam"

that's not good code as we register zafira by default using "reporting-service" container name

**Comment by vdelendik** [comment]
1. there no anymore dedicated reporting service end-point like /zafira-ws or /reporting-service
2. we can reuse as serviceUrl for the ZafiraClient just INFRA_HOST url
3. reportingServiceUrl parameter should be removed from RegisterOrganization job

**Comment by vdelendik** [comment]
done. ZafiraClient adjusted in accordance with new end-point.
**Major note**: service url should be registered in short format starting from zebrunner 1.0 (5.2-qps)

**Comment by okamara** [comment]
Verified. Fixed.
