### ISSUE TITLE
improve build naming for RegisterOrganization job adding "folderName"

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#870]
we have only build number as a build name. We have to add folderName (organization) to identify quickly required build.
"#1"
->
"#1| stage"

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/884

**Comment by ilya-varchenya** [comment]
Test scenario:
1. Run Management_Jobs/RegisterOrganization
2. Check that there's name of organisation (that you wrote in **folderName** field) in build name
It should look like that
![image](https://user-images.githubusercontent.com/44428408/89382778-090e6200-d704-11ea-89bd-c2f361032e3b.png)

**Comment by dhreben** [comment]
Verified
<img width="1178" alt="Screen Shot 2020-08-05 at 11 48 14" src="https://user-images.githubusercontent.com/50950954/89392021-a1f7aa00-d711-11ea-8a41-ecb4c2746b09.png">

**Comment by dhreben** [comment]
**Environment:**
  
-  Jenkins-master:5.1

- QPS_PIPELINE_GIT_BRANCH 5.1

- Infra-branch: develop

**Steps:**
1 .Run Management_Jobs/RegisterOrganization

 **Actual result** :  Build  folderName of RegisterOrganization is empty

**Please see screenshot:**
<img width="1081" alt="Screen Shot 2020-08-19 at 18 24 17" src="https://user-images.githubusercontent.com/50950954/90654729-5da7f600-e249-11ea-9c68-32891cecdd92.png">

**Comment by ilya-varchenya** [comment]
@dhreben, please, reload page after jenkins-job build. Jenkins has quite static pages
This case isn't reproduced for me
![image](https://user-images.githubusercontent.com/44428408/91025846-94dc2580-e602-11ea-891c-25dc4f96a4f5.png)

**Comment by dhreben** [comment]
Tested on jenkins:5.2rc1,qps-infra:develop, pipeline:5.2.
