### ISSUE TITLE
improve build naming for RegisterHubCredentials management job

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#871]
declare extra fields folderName and provider, i.e.:
"#3|stage|selenium"

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/880

**Comment by ilya-varchenya** [comment]
Test scenario:
1. Run Management_Jobs/RegisterHubCredentials with your folder, any provider and any URL (no matter, it could be bla-bla-bla)
2. Name of build should look like like that
![image](https://user-images.githubusercontent.com/44428408/89293754-19bcca80-d667-11ea-8ccf-ac7682ed45bf.png)

**Comment by dhreben** [comment]
Verified
<img width="1174" alt="Screen Shot 2020-08-05 at 11 41 48" src="https://user-images.githubusercontent.com/50950954/89391312-b38c8200-d710-11ea-97bb-2cd96f113f6d.png">
