### ISSUE TITLE
register organizatiion shouldn't override selenium url

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#874]
from time to time during upgrade we have to reregister organization.
For now it has step to register default selenium url:
https://github.com/qaprosoft/qps-pipeline/blob/d2ea175095e50d38e7b5ec1df070a622f151b245/src/com/qaprosoft/jenkins/pipeline/Organization.groovy#L269

we have to update logic and do this call only first time if no appropriate credentials/values registered otherwise we override production values by default one everytime we do register organization call.

for overriding selenium hub value we have dedicated registerHubCredentials job

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/892

**Comment by ilya-varchenya** [comment]
Test scenario:
1. Run RegisterOrganization job
2. Check logs for string _<your_org_name>-selenium_hub was successfully registered_
It means that _<your_org_name>-selenium_hub_ was registrated into credentials
3. Run RegisterOrganization job with the same name
4. Check logs for string _Skip registration of <your_org_name>-selenium_hub _
It means that _<your_org_name>-selenium_hub_ wasn't  REregistrated

**Comment by dhreben** [comment]
**Fixed**.

**Run RegisterOrganization job:**

<img width="1082" alt="Screen Shot 2020-08-28 at 15 38 39" src="https://user-images.githubusercontent.com/50950954/91564954-16f18480-e94a-11ea-850b-3b9453aa843f.png">

**Run RegisterOrganization job with the same name:**

<img width="1115" alt="Screen Shot 2020-08-28 at 16 17 01" src="https://user-images.githubusercontent.com/50950954/91564947-135dfd80-e94a-11ea-9a80-96dbaee6fcfa.png">
