### ISSUE TITLE
unable to register new runs

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-pipeline#876]
Zafira:ui v.1.7.2 | server v.1.7.0
Tested on qaprosoft/carina-demo branch: zafira-client
Run Web-demo test with "carina-core_version=6.4.39-SNAPSHOT" in Configuration
Actual result: unable to register new runs
Error in console log:
2020-08-03 10:54:56 ZafiraEventRegistrar [main] [ERROR] Undefined error during test run registration!
13:54:56  java.lang.NullPointerException: null

**Comment by vdelendik** [comment]
need to define valid pipeline and zafira-client changes to be able to register information as earlier

**Comment by vdelendik** [comment]
fixed. test using latest qaprosoft/carina-demo project.
Also make sure that Reporting Service Url as of now should be registered in a short way, i.e.:
http://my-host-address/

**Comment by okamara** [comment]
Verified. Fixed.
