### ISSUE TITLE
Add support of jenkinsDefaultGitBranch parameter on suite level

### ISSUE THREAD

**Issue by SergeiZagriychuk** [qaprosoft/qps-pipeline#877]
Parameter jenkinsDefaultGitBranch is not supported anymore on TestNG suite level.
It allowed to specify different branches for particular suites.

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/879

**Comment by ilya-varchenya** [comment]
Test scenario:
1. Create some **test_branch** in your forked carina-demo
2. Add **jenkinsDefaultGitBranch** parameter into any job
![image](https://user-images.githubusercontent.com/44428408/89287723-23d9cb80-d65d-11ea-8744-f385cbda8286.png)
3. Create **test_branch2** and be sure that this branch has .xml suite for your job like in **test_branch**
![image](https://user-images.githubusercontent.com/44428408/89288009-9cd92300-d65d-11ea-81c3-947f3d7c51f0.png)
4. Register carina-demo repo with **test_branch**
![image](https://user-images.githubusercontent.com/44428408/89288267-06593180-d65e-11ea-84f3-a97e9e999601.png)
5. Check that your job (in my case it was api-demo-job) has value in branch parameter the same as was set in **jenkinsDefaultGitBranch**
![image](https://user-images.githubusercontent.com/44428408/89288532-7a93d500-d65e-11ea-8a12-1a68e680ca6d.png)
6. Try to run this job. It must be finished with success

**Comment by okamara** [comment]
Tested on qps-infra:develop, jenkins- 5.1, pipeline: develop
Create organization and delete reportingServiceUrl and reportingAccessToken in Credentials
Create Register repository -> onPush job is failed

Error:
![Uploading Screen Shot 2020-08-06 at 3.04.47 PM.png…]()

**Comment by okamara** [comment]
Tested. Done.
