### ISSUE TITLE
Refactor BuildJobFactory to support gradle and maven builds

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#878]
We can use the BuidJobFactory to set the structure for maven, gradle or even docker builds as all of these share some base params like: branch, repo, GITHUB_HOST, etc...

**Comment by sandinosanchez** [comment]
feature delivered in the scope of #864 

Environment:

 - infra-branch: develop

Objective:

 - Verify that the execution of the buildJob is successful for both gradle and maven repositories

Pre-conditions:
 - gitlab account
 - carina-demo repo forked into your github account.
 - [iam-service](https://gitlab.com/zebrunner/ce/iam-service) repo forked into your gitlab account.
  - follow the steps(./zebrunner.sh stop if you have a running instance):
   1. cd jenkins
   2. nano .env
   3. change TAG_JENKINS_SLAVE=latest-alpine > TAG_JENKINS_SLAVE=latest-alpine-jdk11
   4. cd .. && ./zebrunner.sh start

Test scenario 1:

 1. Run RegisterOrganization with your github account or qaprosoft
 2. Run RegisterRepository with carina-demo, runner should be TestNG
 3. Run "Build" job with default params

Test scenario 2:

 1. Go to jenkins > Manage jenkins > Global Properties > Add the following params:
   -  GITHUB_HOST = gitlab.com
   - GITHUB_ORGANIZATION = your-gitlab-account
   -  GITHUB_API_URL = https://gitlab/api/v4
   - GITHUB_HTML_URL = https://gitlab.com/your-gitlab-account/iam-service
 2. Run RegisterOrganizarion with your gitlab account as orgName
 3. Run RegisterRepository with:
   - runnerClass = com.qaprosoft.jenkins.pipeline.runner.gradle.Runner
   - scmHost = gitlab.com
   - repo = iam-service
 4. Run "Build" job with default params

Expected results:

 Test Scenario 1:

   2. onPush job executed successfully.
   3. Build job executed successfully.

 Test Scenario 2:

   3. onPushJob executed successfully.
   4. Build job executed successfully.

**Comment by dhreben** [comment]
**Environment:**

infra-branch: develop
**Objective:**

Verify that the execution of the buildJob is successful for both gradle and maven repositories
**Pre-conditions:**

gitlab account
carina-demo repo forked into your github account.
iam-service repo forked into your gitlab account.
follow the steps(./zebrunner.sh stop if you have a running instance):
cd jenkins
nano .env
change TAG_JENKINS_SLAVE=latest-alpine > TAG_JENKINS_SLAVE=latest-alpine-jdk11
cd .. && ./zebrunner.sh start
**Test scenario 1:**

Run RegisterOrganization with your github account or qaprosoft
Run RegisterRepository with carina-demo, runner should be TestNG

@sandinosanchez When I try to run registerRepository with carina-demo(runner used TestNG) registerRepository with onPush-carina-demo are Failed.

**Logs registerRepository:**

<img width="1162" alt="Screen Shot 2020-08-19 at 15 46 28" src="https://user-images.githubusercontent.com/50950954/90636359-27f81280-e233-11ea-8db2-5b87f4935ddb.png">

**Logs onPush-carina-demo:**

<img width="1216" alt="Screen Shot 2020-08-19 at 15 47 53" src="https://user-images.githubusercontent.com/50950954/90636513-642b7300-e233-11ea-8ad1-0c4f95772736.png">

**Comment by dhreben** [comment]
**Fixed:**
**Environment:**

- Jenkins-master:5.2rc1

- QPS_PIPELINE_GIT_BRANCH 5.2

- Infra-branch: develop

**Test Scenario 1:**

onPush job executed successfully.

<img width="1351" alt="Screen Shot 2020-08-19 at 22 26 57" src="https://user-images.githubusercontent.com/50950954/90680814-1b8fac00-e26b-11ea-87e3-b30d54e6c174.png">

Build job executed successfully.

<img width="1270" alt="Screen Shot 2020-08-19 at 22 28 22" src="https://user-images.githubusercontent.com/50950954/90680955-4da10e00-e26b-11ea-92ba-9e559ed23556.png">

**Test Scenario 2:**

onPushJob executed successfully.

<img width="1307" alt="Screen Shot 2020-08-19 at 22 29 48" src="https://user-images.githubusercontent.com/50950954/90681084-804b0680-e26b-11ea-8922-2df2be8d9a89.png">

Build job executed successfully.

<img width="1387" alt="Screen Shot 2020-08-19 at 22 31 05" src="https://user-images.githubusercontent.com/50950954/90681191-af617800-e26b-11ea-8067-d5dd5bdb4c71.png">
