### ISSUE TITLE
remove optimize_video_recording parameter as not used anymore

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#897]
Configuration.Parameter.OPTIMIZE_VIDEO_RECORDING is not used anymore by carina so it should be removed from pipeline

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/899

**Comment by ilya-varchenya** [comment]
Test scenario:
Register Organisation and Repo, check that everything works as well

**Comment by dhreben** [comment]
Verified
