### ISSUE TITLE
Add possibility to collect all available devices

### ISSUE THREAD

**Issue by maksimsarychau** [qaprosoft/qps-pipeline#9]
Or figure out how to configure them manually. For now only DefaultPool or Any is working.

**Comment by hursevich** [comment]
Use following Groovy script:

import groovy.json.JsonSlurper

def json = new JsonSlurper().parse("https://smule.qaprosoft.com/grid/admin/ProxyInfo".toURL())

json.each {
    println it.configuration.capabilities.browserName
}
