### ISSUE TITLE
minimize custom appium timeouts in default pipeline

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#901]
Android + iOS:
        Configuration.set("capabilities.newCommandTimeout", "180")

Android:
        Configuration.set("capabilities.appWaitDuration", "270000")
        Configuration.set("capabilities.androidInstallTimeout", "270000")
        Configuration.set("capabilities.adbExecTimeout", "270000")

Ideally our pipeline shouldn't provide any custom timeouts. In case of necessity to do it it should be done on exact project private code only

**Comment by vdelendik** [comment]
improvement delivered in 5.2.4 and merged to develop: https://github.com/qaprosoft/qps-pipeline/pull/902
all above timeouts are commented, i.e. default values will be used
newCommandTimeout: 60 (???) no clear explanation for it
appWaitDuration: 20
androidInstallTimeout: 90
adbExecTimeout: 20

**Comment by okamara** [comment]
Tested on client's env. Fixed.
