### ISSUE TITLE
Incorrect link in Testrail result to Zebrunner logs

### ISSUE THREAD

**Issue by dzmitry-pinchuk** [qaprosoft/qps-pipeline#905]
Steps:
1) Launch tests with Testrail integration
2) Open test result in testrail testrun
3) Review link to Zebrunner logs

**Expected result:** https://projectName.zebrunner.com/tests/runs/110530/info/5131967
**Actual result:** https://projectName.zebrunner.com/test-runs/110530/tests/5131967

**Comment by vdelendik** [comment]
fixed. it will be available with in 5.3 rlease (1.1 zebrunner).
