### ISSUE TITLE
remove ugly message in logs "[ERROR] zafiraFields:"

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#906]
seems like temp debug message still present in the pipeline logs.

**Comment by vdelendik** [comment]
fixed.
fix can be tested using QPS_PIPELINE_BRANCH: 5.2.5 or develop.

**Comment by dhreben** [comment]
Fixed:
<img width="730" alt="Screen Shot 2020-10-06 at 17 44 24" src="https://user-images.githubusercontent.com/50950954/95217197-94d36600-07fb-11eb-92ad-efd75694015c.png">
